'use strict';

const { canonicalDigest, canonicalJson } = require('../../../contracts/canonical-json');
const { createRepositoryDefinition } = require('../../../foundation/persistence/owner-repository');

class AftercareStoreError extends Error {
  constructor(code, message) { super(message); this.name = 'AftercareStoreError'; this.code = code; }
}
const fail = (code, message) => { throw new AftercareStoreError(code, message); };

function createAftercareStore(options) {
  if (!options?.schemaManifest || !options.unitOfWork) throw new TypeError('Aftercare Store requires clean persistence dependencies.');
  const now = options.now || Date.now;
  const arca = createRepositoryDefinition({ repositoryId:'arca_aftercare_store', owner:'arca', schemaManifest:options.schemaManifest, statements:{
    list_entries:{kind:'select-all',tableId:'arca_shelf_entries',columns:['shelf_entry_id','shelf_id','structure_kind','status','canonical_identity_revision','canonical_identity_key','current_inventory_revision','current_deck_fact_revision','created_at_ms','terminal_at_ms'],keyColumns:[],safeIntegers:true},
    list_shelves:{kind:'select-all',tableId:'arca_shelves',columns:['shelf_id','name','target_endpoint_id','target_root_location','target_mount_scope_id','target_mount_scope_revision','status','current_standard_revision','current_placement_revision','updated_at_ms'],keyColumns:[],safeIntegers:true},
    find_entry:{kind:'select-one',tableId:'arca_shelf_entries',columns:['shelf_entry_id','shelf_id','structure_kind','status','canonical_identity_revision','canonical_identity_key','current_inventory_revision','current_deck_fact_revision','created_at_ms','terminal_at_ms'],keyColumns:['shelf_entry_id'],safeIntegers:true},
    find_shelf:{kind:'select-one',tableId:'arca_shelves',columns:['shelf_id','name','target_endpoint_id','target_root_location','target_mount_scope_id','target_mount_scope_revision','status','current_standard_revision','current_placement_revision','updated_at_ms'],keyColumns:['shelf_id'],safeIntegers:true},
    find_standard:{kind:'select-one',tableId:'arca_shelf_standard_revisions',columns:['shelf_id','revision','standard_schema_ref','standard_json','standard_digest','effective_at_ms'],keyColumns:['shelf_id','revision'],safeIntegers:true},
    list_all_standards:{kind:'select-all',tableId:'arca_shelf_standard_revisions',columns:['shelf_id','revision','standard_schema_ref','standard_json','standard_digest','effective_at_ms'],keyColumns:[],safeIntegers:true},
    find_placement:{kind:'select-one',tableId:'arca_placement_policy_revisions',columns:['shelf_id','revision','policy_schema_ref','policy_json','policy_digest','effective_at_ms'],keyColumns:['shelf_id','revision'],safeIntegers:true},
    find_identity:{kind:'select-one',tableId:'arca_canonical_identity_revisions',columns:['shelf_entry_id','revision','identity_kind','provider','provider_key','identity_digest','committed_at_ms'],keyColumns:['shelf_entry_id','revision'],safeIntegers:true},
    list_all_identities:{kind:'select-all',tableId:'arca_canonical_identity_revisions',columns:['shelf_entry_id','revision','identity_kind','provider','provider_key','identity_digest','committed_at_ms'],keyColumns:[],safeIntegers:true},
    find_inventory:{kind:'select-one',tableId:'arca_inventory_representations',columns:['shelf_entry_id','revision','representation_digest','source_package_id','committed_at_ms'],keyColumns:['shelf_entry_id','revision'],safeIntegers:true},
    find_ondeck_commit:{kind:'select-one',tableId:'arca_ondeck_commit_receipts',columns:['receipt_id','on_deck_run_id','shelf_entry_id','inventory_revision','deck_fact_revision','control_revision_set_digest','related_disposition_completion_digest','commit_digest','committed_at_ms'],keyColumns:['shelf_entry_id'],safeIntegers:true},
    find_final_decision:{kind:'select-one',tableId:'arca_final_inventory_decisions',columns:['final_inventory_decision_id','on_deck_run_id','shelf_id','placement_revision','target_endpoint_id','target_location','product_manifest_digest','offload_context_digest','related_disposition_set_digest','decision_schema_ref','decision_json','decision_digest','decided_at_ms'],keyColumns:['on_deck_run_id'],safeIntegers:true},
    list_all_inventories:{kind:'select-all',tableId:'arca_inventory_representations',columns:['shelf_entry_id','revision','representation_digest','source_package_id','committed_at_ms'],keyColumns:[],safeIntegers:true},
    list_materials:{kind:'select-all',tableId:'arca_inventory_materials',columns:['shelf_entry_id','inventory_revision','ordinal','material_key','role','episode_claims_schema_ref','episode_claims_json','episode_claim_set_digest','endpoint_id','location','binding_revision','mount_scope_id','inode','fingerprint_algorithm','fingerprint_version','content_fingerprint','digest_hex','size_bytes','active_guard'],keyColumns:['shelf_entry_id','inventory_revision'],safeIntegers:true},
    list_related:{kind:'select-all',tableId:'arca_inventory_related_references',columns:['shelf_entry_id','inventory_revision','reference_id','primary_ordinal','role','reference_kind','material_identity_hint','endpoint_id','location','checksum_hex'],keyColumns:['shelf_entry_id','inventory_revision'],safeIntegers:true},
    list_facts:{kind:'select-all',tableId:'arca_inventory_product_facts',columns:['shelf_entry_id','inventory_revision','fact_kind','fact_revision','fact_schema_ref','fact_json','fact_digest','source_package_id','provenance_digest','committed_at_ms'],keyColumns:['shelf_entry_id','inventory_revision'],safeIntegers:true},
    list_all_facts:{kind:'select-all',tableId:'arca_inventory_product_facts',columns:['shelf_entry_id','inventory_revision','fact_kind','fact_revision','fact_schema_ref','fact_json','fact_digest','source_package_id','provenance_digest','committed_at_ms'],keyColumns:[],safeIntegers:true},
    list_people:{kind:'select-all',tableId:'arca_inventory_person_relations',columns:['relation_id','shelf_entry_id','inventory_revision','person_id','display_name','display_name_normalized','role','relation_source','provider_identity_schema_ref','provider_identity_json','provider_identity_digest','origin_evidence_digest','confidence_class','relation_digest'],keyColumns:['shelf_entry_id','inventory_revision'],safeIntegers:true},
    insert_representation:{kind:'insert',tableId:'arca_inventory_representations',columns:['shelf_entry_id','revision','representation_digest','source_package_id','committed_at_ms']},
    clear_active_material_guards:{kind:'update',tableId:'arca_inventory_materials',setColumns:['active_guard'],keyColumns:['shelf_entry_id','inventory_revision']},
    insert_material:{kind:'insert',tableId:'arca_inventory_materials',columns:['shelf_entry_id','inventory_revision','ordinal','material_key','role','episode_claims_schema_ref','episode_claims_json','episode_claim_set_digest','endpoint_id','location','binding_revision','mount_scope_id','inode','fingerprint_algorithm','fingerprint_version','content_fingerprint','digest_hex','size_bytes','active_guard']},
    insert_related:{kind:'insert',tableId:'arca_inventory_related_references',columns:['shelf_entry_id','inventory_revision','reference_id','primary_ordinal','role','reference_kind','material_identity_hint','endpoint_id','location','checksum_hex']},
    insert_fact:{kind:'insert',tableId:'arca_inventory_product_facts',columns:['shelf_entry_id','inventory_revision','fact_kind','fact_revision','fact_schema_ref','fact_json','fact_digest','source_package_id','provenance_digest','committed_at_ms']},
    insert_person:{kind:'insert',tableId:'arca_inventory_person_relations',columns:['relation_id','shelf_entry_id','inventory_revision','person_id','display_name','display_name_normalized','role','relation_source','provider_identity_schema_ref','provider_identity_json','provider_identity_digest','origin_evidence_digest','confidence_class','relation_digest']},
    advance_inventory:{kind:'update',tableId:'arca_shelf_entries',setColumns:['current_inventory_revision'],keyColumns:['shelf_entry_id'],compareColumns:[{column:'current_inventory_revision',parameter:'expected_current_inventory_revision'}]},
    insert_inventory_commit:{kind:'insert',tableId:'arca_aftercare_inventory_commits',columns:['inventory_commit_id','aftercare_case_id','shelf_entry_id','previous_inventory_revision','new_inventory_revision','control_change_digest','commit_digest','committed_at_ms']},
    find_inventory_commit:{kind:'select-one',tableId:'arca_aftercare_inventory_commits',columns:['inventory_commit_id','aftercare_case_id','shelf_entry_id','previous_inventory_revision','new_inventory_revision','control_change_digest','commit_digest','committed_at_ms'],keyColumns:['aftercare_case_id','new_inventory_revision'],safeIntegers:true},
    list_assessments:{kind:'select-all',tableId:'arca_aftercare_assessments',columns:['assessment_id','shelf_entry_id','inventory_revision','standard_revision','placement_revision','decision_fact_set_digest','care_basis_digest','assessment_kind','result','incident_key','evidence_digest','assessed_at_ms'],keyColumns:['shelf_entry_id'],safeIntegers:true},
    list_all_assessments:{kind:'select-all',tableId:'arca_aftercare_assessments',columns:['assessment_id','shelf_entry_id','inventory_revision','standard_revision','placement_revision','decision_fact_set_digest','care_basis_digest','assessment_kind','result','incident_key','evidence_digest','assessed_at_ms'],keyColumns:[],safeIntegers:true},
    find_assessment:{kind:'select-one',tableId:'arca_aftercare_assessments',columns:['assessment_id','shelf_entry_id','inventory_revision','standard_revision','placement_revision','decision_fact_set_digest','care_basis_digest','assessment_kind','result','incident_key','evidence_digest','assessed_at_ms'],keyColumns:['shelf_entry_id','care_basis_digest','assessment_kind'],safeIntegers:true},
    find_assessment_id:{kind:'select-one',tableId:'arca_aftercare_assessments',columns:['assessment_id','shelf_entry_id','inventory_revision','standard_revision','placement_revision','decision_fact_set_digest','care_basis_digest','assessment_kind','result','incident_key','evidence_digest','assessed_at_ms'],keyColumns:['assessment_id'],safeIntegers:true},
    insert_assessment:{kind:'insert',tableId:'arca_aftercare_assessments',columns:['assessment_id','shelf_entry_id','inventory_revision','standard_revision','placement_revision','decision_fact_set_digest','care_basis_digest','assessment_kind','result','incident_key','evidence_digest','assessed_at_ms']},
    list_findings:{kind:'select-all',tableId:'arca_aftercare_findings',columns:['finding_id','assessment_id','finding_kind','severity','repairability','finding_digest','state','created_at_ms'],keyColumns:[],safeIntegers:true},
    insert_finding:{kind:'insert',tableId:'arca_aftercare_findings',columns:['finding_id','assessment_id','finding_kind','severity','repairability','finding_digest','state','created_at_ms']},
    update_finding:{kind:'update',tableId:'arca_aftercare_findings',setColumns:['state'],keyColumns:['finding_id'],compareColumns:[{column:'state',parameter:'expected_state'}]},
    list_cases:{kind:'select-all',tableId:'arca_aftercare_cases',columns:['aftercare_case_id','shelf_entry_id','finding_set_digest','care_basis_schema_ref','care_basis_json','care_basis_digest','care_requirement_schema_ref','care_requirement_json','care_requirement_digest','state','created_at_ms','terminal_at_ms'],keyColumns:['shelf_entry_id'],safeIntegers:true},
    list_all_cases:{kind:'select-all',tableId:'arca_aftercare_cases',columns:['aftercare_case_id','shelf_entry_id','finding_set_digest','care_basis_schema_ref','care_basis_json','care_basis_digest','care_requirement_schema_ref','care_requirement_json','care_requirement_digest','state','created_at_ms','terminal_at_ms'],keyColumns:[],safeIntegers:true},
    find_case:{kind:'select-one',tableId:'arca_aftercare_cases',columns:['aftercare_case_id','shelf_entry_id','finding_set_digest','care_basis_schema_ref','care_basis_json','care_basis_digest','care_requirement_schema_ref','care_requirement_json','care_requirement_digest','state','created_at_ms','terminal_at_ms'],keyColumns:['aftercare_case_id'],safeIntegers:true},
    insert_case:{kind:'insert',tableId:'arca_aftercare_cases',columns:['aftercare_case_id','shelf_entry_id','finding_set_digest','care_basis_schema_ref','care_basis_json','care_basis_digest','care_requirement_schema_ref','care_requirement_json','care_requirement_digest','state','created_at_ms','terminal_at_ms']},
    update_case:{kind:'update',tableId:'arca_aftercare_cases',setColumns:['state','terminal_at_ms'],keyColumns:['aftercare_case_id'],compareColumns:[{column:'state',parameter:'expected_state'}]},
    insert_basis:{kind:'insert',tableId:'arca_aftercare_case_basis_inputs',columns:['aftercare_case_id','input_kind','owner_domain','aggregate_type','aggregate_id','revision','input_digest']},
    list_basis:{kind:'select-all',tableId:'arca_aftercare_case_basis_inputs',columns:['aftercare_case_id','input_kind','owner_domain','aggregate_type','aggregate_id','revision','input_digest'],keyColumns:['aftercare_case_id'],safeIntegers:true},
    list_commits:{kind:'select-all',tableId:'arca_aftercare_inventory_commits',columns:['inventory_commit_id','aftercare_case_id','shelf_entry_id','previous_inventory_revision','new_inventory_revision','control_change_digest','commit_digest','committed_at_ms'],keyColumns:['shelf_entry_id'],safeIntegers:true},
    list_reservations:{kind:'select-all',tableId:'arca_offdeck_reservations',columns:['reservation_id','review_id','shelf_entry_id','inventory_revision','control_scope_digest','state','created_at_ms','released_at_ms'],keyColumns:['shelf_entry_id'],safeIntegers:true},
  }});
  const foundation = createRepositoryDefinition({repositoryId:'arca_aftercare_foundation',owner:'execution-foundation',schemaManifest:options.schemaManifest,statements:{
    insert_marker:{kind:'insert',tableId:'fx_commit_markers',columns:['commit_marker','effect_id','owner_domain','scope_type','scope_id','commit_digest','result_id','result_schema_ref','result_digest','committed_at_ms']},
    insert_outbox:{kind:'insert',tableId:'fx_outbox',columns:['message_id','producer_domain','message_kind','aggregate_type','aggregate_id','aggregate_revision','dedup_key','consumer_set_digest','intended_consumer_count','payload_schema_ref','payload_json','payload_digest','state','available_at_ms','created_at_ms','all_acked_at_ms']},
  }});
  const read=(body)=>options.unitOfWork.execute([{participantId:'arca_aftercare_read',owner:'arca',repositories:[arca],execute:body}]).arca_aftercare_read;
  const parse=(value,code)=>{try{return JSON.parse(value);}catch{fail(code,'Stored Aftercare JSON is corrupt.');}};
  const mapAssessment=(row)=>row&&Object.freeze({assessmentId:row.assessment_id,shelfEntryId:row.shelf_entry_id,inventoryRevision:Number(row.inventory_revision),standardRevision:Number(row.standard_revision),placementRevision:Number(row.placement_revision),decisionFactSetDigest:row.decision_fact_set_digest,careBasisDigest:row.care_basis_digest,assessmentKind:row.assessment_kind,result:row.result,incidentKey:row.incident_key||null,evidenceDigest:row.evidence_digest,assessedAtMs:Number(row.assessed_at_ms)});
  const mapFinding=(row)=>row&&Object.freeze({findingId:row.finding_id,assessmentId:row.assessment_id,findingKind:row.finding_kind,severity:row.severity,repairability:row.repairability,findingDigest:row.finding_digest,state:row.state,createdAtMs:Number(row.created_at_ms)});
  const mapCase=(row)=>row&&Object.freeze({aftercareCaseId:row.aftercare_case_id,shelfEntryId:row.shelf_entry_id,findingSetDigest:row.finding_set_digest,careBasis:parse(row.care_basis_json,'ARCA_AFTERCARE_BASIS_CORRUPT'),careBasisDigest:row.care_basis_digest,careRequirement:parse(row.care_requirement_json,'ARCA_AFTERCARE_REQUIREMENT_CORRUPT'),careRequirementDigest:row.care_requirement_digest,state:row.state,createdAtMs:Number(row.created_at_ms),terminalAtMs:row.terminal_at_ms===null?null:Number(row.terminal_at_ms)});

  function currentContext(shelfEntryId){return read((context)=>{const repo=context.repository(arca.repositoryId),entry=repo.invoke('find_entry',{shelf_entry_id:shelfEntryId});if(!entry)return null;
    const shelf=repo.invoke('find_shelf',{shelf_id:entry.shelf_id});if(!shelf)return null;const inventoryRevision=Number(entry.current_inventory_revision),standardRevision=Number(shelf.current_standard_revision),placementRevision=Number(shelf.current_placement_revision);
    const inventory=repo.invoke('find_inventory',{shelf_entry_id:shelfEntryId,revision:inventoryRevision}),standard=repo.invoke('find_standard',{shelf_id:shelf.shelf_id,revision:standardRevision}),placement=repo.invoke('find_placement',{shelf_id:shelf.shelf_id,revision:placementRevision}),identity=repo.invoke('find_identity',{shelf_entry_id:shelfEntryId,revision:Number(entry.canonical_identity_revision)}),onDeckCommit=repo.invoke('find_ondeck_commit',{shelf_entry_id:shelfEntryId}),initialPlacementDecision=onDeckCommit?repo.invoke('find_final_decision',{on_deck_run_id:onDeckCommit.on_deck_run_id}):null;
    if(!inventory||!standard||!placement||!identity)fail('ARCA_AFTERCARE_CURRENT_BASIS_BROKEN','Shelf Entry current Aftercare Basis is incomplete.');
    return Object.freeze({entry:Object.freeze({...entry,current_inventory_revision:inventoryRevision,current_deck_fact_revision:Number(entry.current_deck_fact_revision)}),shelf:Object.freeze({...shelf,current_standard_revision:standardRevision,current_placement_revision:placementRevision}),inventory:Object.freeze(inventory),standard:Object.freeze({...standard,value:parse(standard.standard_json,'ARCA_AFTERCARE_STANDARD_CORRUPT')}),placement:Object.freeze({...placement,value:parse(placement.policy_json,'ARCA_AFTERCARE_PLACEMENT_CORRUPT')}),identity:Object.freeze(identity),initialPlacementDecision:initialPlacementDecision?Object.freeze({...initialPlacementDecision,placement_revision:Number(initialPlacementDecision.placement_revision)}):null,materials:Object.freeze(repo.invoke('list_materials',{shelf_entry_id:shelfEntryId,inventory_revision:inventoryRevision})),related:Object.freeze(repo.invoke('list_related',{shelf_entry_id:shelfEntryId,inventory_revision:inventoryRevision})),facts:Object.freeze(repo.invoke('list_facts',{shelf_entry_id:shelfEntryId,inventory_revision:inventoryRevision}).map((row)=>Object.freeze({...row,value:parse(row.fact_json,'ARCA_AFTERCARE_FACT_CORRUPT')}))),people:Object.freeze(repo.invoke('list_people',{shelf_entry_id:shelfEntryId,inventory_revision:inventoryRevision})),reservations:Object.freeze(repo.invoke('list_reservations',{shelf_entry_id:shelfEntryId}))});});}

  function inventoryMaterials(shelfEntryId, inventoryRevision) {
    if (typeof shelfEntryId !== 'string' || !shelfEntryId ||
        !Number.isSafeInteger(Number(inventoryRevision)) || Number(inventoryRevision) < 1) {
      fail('ARCA_AFTERCARE_INVENTORY_SCOPE_INVALID',
        'Aftercare historical Inventory scope is invalid.');
    }
    return read((context) => Object.freeze(context.repository(arca.repositoryId)
      .invoke('list_materials', {
        shelf_entry_id:shelfEntryId,
        inventory_revision:Number(inventoryRevision),
      }).map((item) => Object.freeze(item))));
  }

  function commitAssessmentSet(value){const committedAt=now();return options.unitOfWork.execute([{participantId:'arca_aftercare_assessment_commit',owner:'arca',repositories:[arca],execute(context){const repo=context.repository(arca.repositoryId),existing=[];
    for(const item of value.assessments){let row=repo.invoke('find_assessment_id',{assessment_id:item.assessmentId});if(!row){repo.invoke('insert_assessment',{assessment_id:item.assessmentId,shelf_entry_id:value.shelfEntryId,inventory_revision:value.inventoryRevision,standard_revision:value.standardRevision,placement_revision:value.placementRevision,decision_fact_set_digest:value.decisionFactSetDigest,care_basis_digest:value.careBasisDigest,assessment_kind:item.assessmentKind,result:item.result,incident_key:item.incidentKey||null,evidence_digest:item.evidenceDigest,assessed_at_ms:committedAt});row=repo.invoke('find_assessment_id',{assessment_id:item.assessmentId});
      for(const finding of item.findings||[])repo.invoke('insert_finding',{finding_id:finding.findingId,assessment_id:item.assessmentId,finding_kind:finding.findingKind,severity:finding.severity,repairability:finding.repairability,finding_digest:finding.findingDigest,state:'open',created_at_ms:committedAt});}
      existing.push(mapAssessment(row));}
    return Object.freeze({assessments:Object.freeze(existing),committedAtMs:committedAt});}}]).arca_aftercare_assessment_commit;}

  function createCase(value){const at=now(),caseId='arca-care-'+canonicalDigest({shelfEntryId:value.shelfEntryId,careBasisDigest:value.careBasis.digest,findingSetDigest:value.findingSetDigest,careRequirementDigest:value.careRequirement.digest}).slice(0,40),marker='arca-aftercare-case-'+caseId;
    const existing=read((context)=>context.repository(arca.repositoryId).invoke('list_cases',{shelf_entry_id:value.shelfEntryId}).map(mapCase).find((item)=>item.state==='active'));
    if(existing){if(existing.careBasisDigest===value.careBasis.digest&&existing.findingSetDigest===value.findingSetDigest)return existing;fail('ARCA_AFTERCARE_ACTIVE_CASE_CONFLICT','Shelf Entry already has another active Aftercare Case.');}
    const payload={aftercareCaseId:caseId,shelfEntryId:value.shelfEntryId,careBasisDigest:value.careBasis.digest,careRequirementDigest:value.careRequirement.digest,state:'active'},payloadDigest=canonicalDigest(payload),consumers=canonicalDigest([]);
    options.unitOfWork.execute([{participantId:'arca_aftercare_case_domain',owner:'arca',repositories:[arca],execute(context){const repo=context.repository(arca.repositoryId);if(repo.invoke('list_reservations',{shelf_entry_id:value.shelfEntryId}).some((item)=>item.state==='active'))fail('ARCA_AFTERCARE_MODIFICATION_FENCED','Off-deck Reservation prevents a new Aftercare Case.');repo.invoke('insert_case',{aftercare_case_id:caseId,shelf_entry_id:value.shelfEntryId,finding_set_digest:value.findingSetDigest,care_basis_schema_ref:value.careBasis.schemaRef,care_basis_json:canonicalJson(value.careBasis),care_basis_digest:value.careBasis.digest,care_requirement_schema_ref:value.careRequirement.schemaRef,care_requirement_json:canonicalJson(value.careRequirement),care_requirement_digest:value.careRequirement.digest,state:'active',created_at_ms:at,terminal_at_ms:null});for(const input of value.basisInputs)repo.invoke('insert_basis',{aftercare_case_id:caseId,input_kind:input.inputKind,owner_domain:input.ownerDomain,aggregate_type:input.aggregateType,aggregate_id:input.aggregateId,revision:input.revision,input_digest:input.inputDigest});}},
      {participantId:'arca_aftercare_case_foundation',owner:'execution-foundation',boundBusinessOwner:'arca',repositories:[foundation],execute(context){const repo=context.repository(foundation.repositoryId);repo.invoke('insert_marker',{commit_marker:marker,effect_id:null,owner_domain:'arca',scope_type:'aftercare_case',scope_id:caseId,commit_digest:payloadDigest,result_id:null,result_schema_ref:null,result_digest:null,committed_at_ms:at});repo.invoke('insert_outbox',{message_id:'arca-aftercare-case-message-'+canonicalDigest(caseId).slice(0,32),producer_domain:'arca',message_kind:'arca.aftercare.case.created',aggregate_type:'aftercare_case',aggregate_id:caseId,aggregate_revision:1,dedup_key:marker,consumer_set_digest:consumers,intended_consumer_count:0,payload_schema_ref:'helix://arca/messages/AftercareCaseCreated/v1',payload_json:canonicalJson(payload),payload_digest:payloadDigest,state:'tombstoned',available_at_ms:at,created_at_ms:at,all_acked_at_ms:null});}}]);return getCase(caseId);}
  function terminateCase(caseId,state){if(!['resolved','invalidated','unresolved'].includes(state))fail('ARCA_AFTERCARE_CASE_STATE','Aftercare terminal state is invalid.');return options.unitOfWork.execute([{participantId:'arca_aftercare_case_terminal',owner:'arca',repositories:[arca],execute(context){const repo=context.repository(arca.repositoryId),caseRow=repo.invoke('find_case',{aftercare_case_id:caseId});if(!caseRow)fail('ARCA_AFTERCARE_CASE_MISSING','Aftercare Case is absent.');const changed=repo.invoke('update_case',{state,terminal_at_ms:now(),aftercare_case_id:caseId,expected_state:'active'});if(changed.changes!==1){const current=repo.invoke('find_case',{aftercare_case_id:caseId});if(!current||current.state!==state)fail('ARCA_AFTERCARE_CASE_CAS','Aftercare Case terminal CAS failed.');}if(state==='resolved'){const assessmentIds=new Set(repo.invoke('list_assessments',{shelf_entry_id:caseRow.shelf_entry_id}).filter((item)=>item.care_basis_digest===caseRow.care_basis_digest).map((item)=>item.assessment_id));for(const finding of repo.invoke('list_findings',{})){if(finding.state!=='open'||!assessmentIds.has(finding.assessment_id))continue;repo.invoke('update_finding',{state:'resolved',finding_id:finding.finding_id,expected_state:'open'});}}return mapCase(repo.invoke('find_case',{aftercare_case_id:caseId}));}}]).arca_aftercare_case_terminal;}
  function getCase(caseId){return read((context)=>mapCase(context.repository(arca.repositoryId).invoke('find_case',{aftercare_case_id:caseId})));}
  function commitInventory(value,controlParticipant){const at=now(),previous=Number(value.previousInventoryRevision),next=previous+1,commitId='arca-aftercare-inventory-'+canonicalDigest({caseId:value.aftercareCaseId,shelfEntryId:value.shelfEntryId,previous,representationDigest:value.representationDigest}).slice(0,40),commitDigest=canonicalDigest({schema:'arca.aftercare-inventory-commit@1',commitId,caseId:value.aftercareCaseId,shelfEntryId:value.shelfEntryId,previous,next,representationDigest:value.representationDigest,controlChangeDigest:value.controlChangeDigest}),marker='arca-aftercare-inventory-marker-'+canonicalDigest(commitId).slice(0,32);
    const prior=read((context)=>context.repository(arca.repositoryId).invoke('find_inventory_commit',{aftercare_case_id:value.aftercareCaseId,new_inventory_revision:next}));if(prior){if(prior.commit_digest!==commitDigest)fail('ARCA_AFTERCARE_INVENTORY_REPLAY_CONFLICT','Aftercare Inventory replay conflicts with the committed revision.');return Object.freeze({...prior,previousInventoryRevision:Number(prior.previous_inventory_revision),newInventoryRevision:Number(prior.new_inventory_revision)});}
    const participants=[];if(controlParticipant)participants.push(controlParticipant);participants.push({participantId:'arca_aftercare_inventory_domain',owner:'arca',repositories:[arca],execute(context){const repo=context.repository(arca.repositoryId),entry=repo.invoke('find_entry',{shelf_entry_id:value.shelfEntryId});if(!entry||Number(entry.current_inventory_revision)!==previous)fail('ARCA_AFTERCARE_INVENTORY_STALE','Shelf Entry Inventory changed before Aftercare commit.');const inventory=repo.invoke('find_inventory',{shelf_entry_id:value.shelfEntryId,revision:previous});
      repo.invoke('insert_representation',{shelf_entry_id:value.shelfEntryId,revision:next,representation_digest:value.representationDigest,source_package_id:inventory.source_package_id,committed_at_ms:at});
      repo.invoke('clear_active_material_guards',{active_guard:0,shelf_entry_id:value.shelfEntryId,inventory_revision:previous});
      value.materials.forEach((item,index)=>repo.invoke('insert_material',{shelf_entry_id:value.shelfEntryId,inventory_revision:next,ordinal:index,material_key:item.material_key,role:item.role,episode_claims_schema_ref:item.episode_claims_schema_ref,episode_claims_json:item.episode_claims_json,episode_claim_set_digest:item.episode_claim_set_digest,endpoint_id:item.endpoint_id,location:item.location,binding_revision:Number(item.binding_revision),mount_scope_id:item.mount_scope_id,inode:item.inode,fingerprint_algorithm:item.fingerprint_algorithm,fingerprint_version:String(item.fingerprint_version),content_fingerprint:item.content_fingerprint,digest_hex:item.digest_hex,size_bytes:Number(item.size_bytes),active_guard:item.role==='primary_payload'?1:0}));
      value.related.forEach((item)=>repo.invoke('insert_related',{shelf_entry_id:value.shelfEntryId,inventory_revision:next,reference_id:item.reference_id,primary_ordinal:Number(item.primary_ordinal),role:item.role,reference_kind:item.reference_kind,material_identity_hint:item.material_identity_hint,endpoint_id:item.endpoint_id,location:item.location,checksum_hex:item.checksum_hex}));
      value.facts.forEach((item)=>repo.invoke('insert_fact',{shelf_entry_id:value.shelfEntryId,inventory_revision:next,fact_kind:item.fact_kind,fact_revision:Number(item.fact_revision),fact_schema_ref:item.fact_schema_ref,fact_json:item.fact_json,fact_digest:item.fact_digest,source_package_id:item.source_package_id,provenance_digest:item.provenance_digest,committed_at_ms:at}));
      value.people.forEach((item)=>repo.invoke('insert_person',{relation_id:item.relation_id,shelf_entry_id:value.shelfEntryId,inventory_revision:next,person_id:item.person_id,display_name:item.display_name,display_name_normalized:item.display_name_normalized,role:item.role,relation_source:item.relation_source,provider_identity_schema_ref:item.provider_identity_schema_ref,provider_identity_json:item.provider_identity_json,provider_identity_digest:item.provider_identity_digest,origin_evidence_digest:item.origin_evidence_digest,confidence_class:item.confidence_class,relation_digest:item.relation_digest}));
      const advanced=repo.invoke('advance_inventory',{current_inventory_revision:next,shelf_entry_id:value.shelfEntryId,expected_current_inventory_revision:previous});if(advanced.changes!==1)fail('ARCA_AFTERCARE_INVENTORY_CAS','Shelf Entry Inventory pointer CAS failed.');repo.invoke('insert_inventory_commit',{inventory_commit_id:commitId,aftercare_case_id:value.aftercareCaseId,shelf_entry_id:value.shelfEntryId,previous_inventory_revision:previous,new_inventory_revision:next,control_change_digest:value.controlChangeDigest,commit_digest:commitDigest,committed_at_ms:at});return next;}});
    participants.push({participantId:'arca_aftercare_inventory_foundation',owner:'execution-foundation',boundBusinessOwner:'arca',repositories:[foundation],execute(context){context.repository(foundation.repositoryId).invoke('insert_marker',{commit_marker:marker,effect_id:null,owner_domain:'arca',scope_type:'aftercare_inventory',scope_id:commitId,commit_digest:commitDigest,result_id:null,result_schema_ref:null,result_digest:null,committed_at_ms:at});}});options.unitOfWork.execute(participants);return Object.freeze({inventory_commit_id:commitId,aftercare_case_id:value.aftercareCaseId,shelf_entry_id:value.shelfEntryId,previous_inventory_revision:previous,new_inventory_revision:next,control_change_digest:value.controlChangeDigest,commit_digest:commitDigest,committed_at_ms:at,previousInventoryRevision:previous,newInventoryRevision:next});}
  function history(shelfEntryId){return read((context)=>{const repo=context.repository(arca.repositoryId),assessments=repo.invoke('list_assessments',{shelf_entry_id:shelfEntryId}).map(mapAssessment).sort((a,b)=>b.assessedAtMs-a.assessedAtMs),ids=new Set(assessments.map((x)=>x.assessmentId)),findings=repo.invoke('list_findings',{}).filter((x)=>ids.has(x.assessment_id)).map(mapFinding).sort((a,b)=>b.createdAtMs-a.createdAtMs),cases=repo.invoke('list_cases',{shelf_entry_id:shelfEntryId}).map(mapCase).map((item)=>Object.freeze({...item,basisInputs:Object.freeze(repo.invoke('list_basis',{aftercare_case_id:item.aftercareCaseId}).map((row)=>Object.freeze({inputKind:row.input_kind,ownerDomain:row.owner_domain,aggregateType:row.aggregate_type,aggregateId:row.aggregate_id,revision:Number(row.revision),inputDigest:row.input_digest})))})).sort((a,b)=>b.createdAtMs-a.createdAtMs),commits=repo.invoke('list_commits',{shelf_entry_id:shelfEntryId}).map((x)=>Object.freeze({inventoryCommitId:x.inventory_commit_id,aftercareCaseId:x.aftercare_case_id,previousInventoryRevision:Number(x.previous_inventory_revision),newInventoryRevision:Number(x.new_inventory_revision),commitDigest:x.commit_digest,committedAtMs:Number(x.committed_at_ms)}));return Object.freeze({assessments:Object.freeze(assessments),findings:Object.freeze(findings),cases:Object.freeze(cases),commits:Object.freeze(commits)});});}
  function healthProjectionInputs(shelfEntryIds){const wanted=new Set(shelfEntryIds);return read((context)=>{const repo=context.repository(arca.repositoryId),entries=repo.invoke('list_entries',{}).filter((row)=>wanted.has(row.shelf_entry_id)&&row.status==='active'),shelves=new Map(repo.invoke('list_shelves',{}).map((row)=>[row.shelf_id,row])),standards=repo.invoke('list_all_standards',{}),facts=repo.invoke('list_all_facts',{}),identities=repo.invoke('list_all_identities',{}),inventories=repo.invoke('list_all_inventories',{}),assessments=repo.invoke('list_all_assessments',{}).map(mapAssessment),assessmentIds=new Set(assessments.filter((row)=>wanted.has(row.shelfEntryId)).map((row)=>row.assessmentId)),findings=repo.invoke('list_findings',{}).filter((row)=>assessmentIds.has(row.assessment_id)).map(mapFinding),cases=repo.invoke('list_all_cases',{}).map(mapCase);
    return Object.freeze(entries.map((entry)=>{const shelf=shelves.get(entry.shelf_id);if(!shelf)return null;const standard=standards.find((row)=>row.shelf_id===entry.shelf_id&&Number(row.revision)===Number(shelf.current_standard_revision)),inventoryRevision=Number(entry.current_inventory_revision),identity=identities.find((row)=>row.shelf_entry_id===entry.shelf_entry_id&&Number(row.revision)===Number(entry.canonical_identity_revision)),inventory=inventories.find((row)=>row.shelf_entry_id===entry.shelf_entry_id&&Number(row.revision)===inventoryRevision);if(!identity||!inventory||!standard)return null;const entryFacts=facts.filter((row)=>row.shelf_entry_id===entry.shelf_entry_id&&Number(row.inventory_revision)===inventoryRevision),factDigests=entryFacts.filter((row)=>row.fact_kind!=='decision_fact').map((row)=>row.fact_digest).sort(),decisionFactDigests=entryFacts.filter((row)=>row.fact_kind==='decision_fact').map((row)=>row.fact_digest).sort(),entryAssessments=assessments.filter((row)=>row.shelfEntryId===entry.shelf_entry_id),entryAssessmentIds=new Set(entryAssessments.map((row)=>row.assessmentId));return Object.freeze({shelfEntryId:entry.shelf_entry_id,structureKind:entry.structure_kind,inventoryRevision,standardRevision:Number(shelf.current_standard_revision),placementRevision:Number(shelf.current_placement_revision),canonicalIdentityDigest:identity.identity_digest,sourcePackageId:inventory.source_package_id,standardValue:parse(standard.standard_json,'ARCA_AFTERCARE_STANDARD_CORRUPT'),factDigests:Object.freeze(factDigests),decisionFactDigests:Object.freeze(decisionFactDigests),history:Object.freeze({assessments:Object.freeze(entryAssessments.sort((a,b)=>b.assessedAtMs-a.assessedAtMs)),findings:Object.freeze(findings.filter((row)=>entryAssessmentIds.has(row.assessmentId)).sort((a,b)=>b.createdAtMs-a.createdAtMs)),cases:Object.freeze(cases.filter((row)=>row.shelfEntryId===entry.shelf_entry_id).sort((a,b)=>b.createdAtMs-a.createdAtMs)),commits:Object.freeze([])})});}).filter(Boolean));});}
  function listEntryPage(cursor,limit=100){return read((context)=>context.repository(arca.repositoryId).invoke('list_entries',{}).filter((x)=>x.status==='active'&&(cursor===null||x.shelf_entry_id>cursor)).sort((a,b)=>a.shelf_entry_id.localeCompare(b.shelf_entry_id)).slice(0,limit).map((x)=>Object.freeze({cursor:x.shelf_entry_id,scope:Object.freeze({shelfEntryId:x.shelf_entry_id})})));}
  return Object.freeze({currentContext,inventoryMaterials,commitAssessmentSet,createCase,terminateCase,getCase,commitInventory,history,healthProjectionInputs,listEntryPage});
}

module.exports=Object.freeze({AftercareStoreError,createAftercareStore});
