'use strict';
const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const test=require('node:test');
const {createBackup,initializeCleanData,inspectReadiness,restoreBackup,verifyBackup}=require('../../scripts/helix-operational-safety');
const secretRoot='p13-test-secret-root-0123456789abcdef';
const roots=[];const root=()=>{const value=fs.mkdtempSync(path.join(os.tmpdir(),'helix-p13-'));roots.push(value);return value;};test.after(()=>roots.forEach((value)=>fs.rmSync(value,{recursive:true,force:true})));
test('clean initialization rejects missing confirmation and backs up old bytes before replacement',()=>{const r=root(),data=path.join(r,'data'),backup=path.join(r,'backup');fs.mkdirSync(data);fs.writeFileSync(path.join(data,'legacy.json'),'legacy');assert.throws(()=>initializeCleanData({dataDir:data,backupDir:backup,confirmation:'wrong'}),/CONFIRMATION/);const result=initializeCleanData({dataDir:data,backupDir:backup,confirmation:'INITIALIZE_HELIX_CLEAN_V1',now:()=>1700000000000,secretRoot});assert.equal(result.generation,'helix-clean-v1');assert.equal(result.tableCount,179);assert.match(result.adminApiKey,/^sd_/);assert.equal(verifyBackup(backup).files[0].path,'legacy.json');assert.equal(fs.existsSync(path.join(data,'legacy.json')),false);assert.equal(fs.existsSync(path.join(data,'shelfdeck.db')),true);});
test('backup digest tampering is rejected and restore never overwrites a non-empty target',()=>{const r=root(),source=path.join(r,'source'),backup=path.join(r,'backup'),target=path.join(r,'target');fs.mkdirSync(source);fs.writeFileSync(path.join(source,'a.txt'),'alpha');createBackup({sourceDir:source,backupDir:backup,createdAt:'2026-07-23T00:00:00Z'});fs.mkdirSync(target);fs.writeFileSync(path.join(target,'keep.txt'),'keep');assert.throws(()=>restoreBackup({backupDir:backup,targetDir:target}),/NOT_EMPTY/);fs.rmSync(target,{recursive:true});const restored=restoreBackup({backupDir:backup,targetDir:target});assert.equal(restored.fileCount,1);fs.writeFileSync(path.join(backup,'a.txt'),'tampered');assert.throws(()=>verifyBackup(backup),/DIGEST_MISMATCH/);});
test('readiness accepts only clean DB, authenticated credential and built Admin surface',()=>{const r=root(),data=path.join(r,'data'),admin=path.join(r,'admin');initializeCleanData({dataDir:data,confirmation:'INITIALIZE_HELIX_CLEAN_V1',secretRoot});assert.equal(inspectReadiness({dataDir:data,adminDistDir:admin,secretRoot}).state,'not_ready');fs.mkdirSync(admin);fs.writeFileSync(path.join(admin,'index.html'),'<!doctype html>');const ready=inspectReadiness({dataDir:data,adminDistDir:admin,secretRoot});assert.equal(ready.state,'ready');assert.deepEqual({tables:ready.tableCount,routes:ready.routeCount,surfaces:ready.uiSurfaceCount},{tables:179,routes:114,surfaces:18});assert.equal(inspectReadiness({dataDir:data,adminDistDir:admin,secretRoot:'wrong-secret-root-that-is-still-long-enough'}).state,'not_ready');});
test('P13 sources contain no legacy state import, compatibility or dual path',()=>{for(const file of ['scripts/helix-clean-init.js','scripts/helix-operational-safety.js','src/helix/composition/createHelixApplication.js']){const source=fs.readFileSync(path.join(__dirname,'../../',file),'utf8');assert.doesNotMatch(source,/helixCleanState|legacy runtime fallback|dual[-_ ]?(read|write|run)|src\/app/i,file);}});
