'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),test=require('node:test'),Database=require('better-sqlite3');
const {createStartupRecovery}=require('../../src/helix/foundation/execution/startup-recovery'); const {openSqliteKernel}=require('../../src/helix/foundation/persistence/sqlite-kernel'); const {createSqliteUnitOfWork}=require('../../src/helix/foundation/persistence/sqlite-unit-of-work');
const g=path.resolve(__dirname,'../../src/helix/foundation/persistence/generated'),ddl=fs.readFileSync(path.join(g,'clean-schema.sql'),'utf8'),manifest=JSON.parse(fs.readFileSync(path.join(g,'clean-schema.manifest.json'),'utf8'));
function fixture(run,settings={}){const root=fs.mkdtempSync(path.join(os.tmpdir(),'helix-startup-')),dbp=path.join(root,'db');const kernel=openSqliteKernel({Database,databasePath:dbp,schemaDdl:ddl,schemaManifest:manifest,now:()=>1700000005000});
 kernel.runPrimitive(t=>{t.prepare("INSERT INTO fx_supporting_works(work_id,state) VALUES('w','running')").run();t.prepare("INSERT INTO fx_work_attempts(attempt_id,work_id,state) VALUES('wa','w','running')").run();t.prepare("INSERT INTO fx_workflow_plans(plan_id,attempt_id,state) VALUES('p','wa','planned')").run();
 t.prepare("INSERT INTO fx_plan_nodes(plan_id,node_id,effect_class,retry_policy_ref,timeout_policy_ref) VALUES('p','n',?,?,?)").run(settings.effectClass||'pure_observation','r','t');t.prepare("INSERT INTO fx_workflow_events(event_id,plan_id,node_id,work_id,attempt_id,owner_domain,capability_ref,state) VALUES('e','p','n','w','wa','libra','libra.fixture@1','executing')").run();
 t.prepare("INSERT INTO fx_event_attempts(event_attempt_id,event_id,ordinal,state) VALUES('ea','e',1,'executing')").run();if(settings.journal)t.prepare("INSERT INTO fx_effect_journal(effect_id,event_attempt_id,effect_class,idempotency_key,intent_digest,state,updated_at_ms) VALUES('fx','ea',?,'k',?,'intended',1)").run(settings.effectClass,'a'.repeat(64));if(settings.circuit)t.prepare("INSERT INTO fx_circuit_states(circuit_key,state,reason_code,evidence_digest,opened_at_ms) VALUES('foundation/event-dispatch','open','X',?,1)").run('b'.repeat(64));});
 const recovery=createStartupRecovery({schemaManifest:manifest,unitOfWork:createSqliteUnitOfWork({kernel}),registry:{resolve:()=>({})},policyRegistry:{bindingFor:()=>({})},integrityVerifier:{verify:()=>({ok:settings.integrity!==false})},effectReconciler:{reconcile:async()=>({decision:'continue_forward',evidenceDigest:'c'.repeat(64)})}});try{return run(recovery);}finally{kernel.close();fs.rmSync(root,{recursive:true,force:true});}}
test('bootstrapping blocks supply and pure crash classifies safe retry without resetting facts',async()=>fixture(async r=>{assert.equal(r.readiness().state,'bootstrapping');const x=await r.recover();assert.equal(x.state,'ready');assert.equal(x.actions[0].decision,'safe_retry');assert.equal(x.recoveredInMemoryPermits,0);}));
test('non-pure executing Event uses exact effect reconciler',async()=>fixture(async r=>{const x=await r.recover();assert.equal(x.actions[0].decision,'continue_forward');},{effectClass:'material_commit',journal:true}));
test('non-pure crash before durable intent is distinguished from unknown effect point',async()=>fixture(async r=>{const x=await r.recover();assert.equal(x.actions[0].decision,'safe_retry_before_intent');},{effectClass:'external_request'}));
test('global Circuit and integrity failure keep normal supply faulted',async()=>{await fixture(async r=>{const x=await r.recover();assert.equal(x.state,'faulted');assert.equal(x.normalSupplyAllowed,false);},{circuit:true});await fixture(async r=>assert.equal((await r.recover()).state,'faulted'),{integrity:false});});
