'use strict';

const assert=require('node:assert/strict');const test=require('node:test');const {canonicalDigest}=require('../../src/helix/contracts/canonical-json');const {applyRunLifecycleDecision,buildRunLifecycleDecision,buildRunLifecycleResult,runStateDigest}=require('../../src/helix/domains/libra/model/run-lifecycle-contracts');const D=(value)=>canonicalDigest({value});
function current(state='active',revision=1){const value={libraRunId:D('run'),stateRevision:revision,state,acceptanceSpecId:'spec-1',executionBasisDigest:D('basis'),runScopeDigest:D('scope'),priorityClass:'normal',priorityIntentDigest:D('priority'),transitionKind:'admitted',transitionEvidenceDigest:D('admission')};value.stateDigest=runStateDigest(value);return value;}
function decision(run,transitionKind,extra={}){return buildRunLifecycleDecision({libraRunId:run.libraRunId,expectedStateRevision:run.stateRevision,expectedStateDigest:run.stateDigest,transitionKind,newPriority:transitionKind==='set_priority'?{priorityClass:'expedited',priorityIntentDigest:D('expedite')}:undefined,transitionEvidence:{schemaRef:'helix://contracts/evidence/fixture/v1',evidenceId:'evidence-1',evidenceDigest:D(transitionKind)},expectedAdmissionHeadRevision:3,expectedActiveScopeSetDigest:D('active-set'),...extra});}
test('applies the closed active-suspended-active lifecycle without changing immutable Run basis',()=>{const active=current(),suspended=applyRunLifecycleDecision(active,decision(active,'suspend')),resumed=applyRunLifecycleDecision(suspended,decision(suspended,'resume'));assert.equal(suspended.state,'suspended');assert.equal(resumed.state,'active');assert.equal(resumed.executionBasisDigest,active.executionBasisDigest);assert.equal(resumed.stateRevision,3);});
test('reprioritizes only the Run and keeps state and Execution Basis unchanged',()=>{const run=current(),next=applyRunLifecycleDecision(run,decision(run,'set_priority'));assert.equal(next.state,'active');assert.equal(next.priorityClass,'expedited');assert.equal(next.executionBasisDigest,run.executionBasisDigest);assert.equal(next.transitionKind,'reprioritized');});
test('freezes from active or suspended and rejects every automatic transition out of frozen',()=>{for(const run of [current(),current('suspended')]){const frozen=applyRunLifecycleDecision(run,decision(run,'freeze'));assert.equal(frozen.state,'frozen');for(const transition of ['resume','suspend','freeze','set_priority','complete'])assert.throws(()=>applyRunLifecycleDecision(frozen,decision(frozen,transition)),(error)=>error.code==='P9_RUN_LIFECYCLE_ILLEGAL_STATE');}});
test('allows complete only from active and forms the exact durable Result digest',()=>{const run=current(),completed=applyRunLifecycleDecision(run,decision(run,'complete')),result=buildRunLifecycleResult({decisionId:decision(run,'complete').decisionId,libraRunId:run.libraRunId,previousStateRevision:run.stateRevision,previousStateDigest:run.stateDigest,committedState:completed.state,committedStateRevision:completed.stateRevision,committedStateDigest:completed.stateDigest,committedAdmissionHeadRevision:4,activeScopeSetDigest:D('empty-set'),deliveryReceiptId:'receipt-1',terminalAtMs:100});assert.equal(completed.state,'completed');assert.equal(result.resultDigest,canonicalDigest(Object.fromEntries(Object.entries(result).filter(([key])=>key!=='resultDigest'))));assert.throws(()=>applyRunLifecycleDecision(current('suspended'),decision(current('suspended'),'complete')));});
test('rejects priority authority on other transition variants and stale current Run fences',()=>{const run=current();assert.throws(()=>buildRunLifecycleDecision({libraRunId:run.libraRunId,expectedStateRevision:1,expectedStateDigest:run.stateDigest,transitionKind:'suspend',newPriority:{priorityClass:'expedited',priorityIntentDigest:D('x')},transitionEvidence:{schemaRef:'e',evidenceId:'e',evidenceDigest:D('e')},expectedAdmissionHeadRevision:1,expectedActiveScopeSetDigest:D('set')}),(error)=>error.code==='P9_RUN_LIFECYCLE_PRIORITY');const stale=decision(run,'suspend',{expectedStateRevision:2});assert.throws(()=>applyRunLifecycleDecision(run,stale),(error)=>error.code==='P9_RUN_LIFECYCLE_STALE');});
