'use strict';

const assert=require('node:assert/strict');
const test=require('node:test');
const {canonicalDigest}=require('../../src/helix/contracts/canonical-json');
const {RECOVERY_OFFSETS,applyRunLifecycleDecision,buildRunLifecycleDecision,buildRunLifecycleResult,runStateDigest}=require('../../src/helix/domains/libra/model/run-lifecycle-contracts');
const D=(value)=>canonicalDigest({value});
function withDigest(value,key){return {...value,[key]:canonicalDigest(value)};}
function policy(){return withDigest({policyRef:'libra.run-recovery.beta@1',policyRevision:1,assessmentOffsetsMs:RECOVERY_OFFSETS,maxRecoveryAssessments:5,heavyPermitAllowed:false,frozenAutoResumeAllowed:false},'policyDigest');}
function current(state='active',revision=1,extra={}){const value={libraRunId:D('run'),stateRevision:revision,state,acceptanceSpecId:'spec-1',executionBasisDigest:D('basis'),runScopeDigest:D('scope'),priorityClass:'normal',priorityIntentDigest:D('priority'),transitionKind:'admitted',transitionEvidenceDigest:D('admission'),recoveryPolicyRef:null,recoveryPolicyDigest:null,suspensionStartedAtMs:null,recoveryAttemptOrdinal:0,recoveryNextDueAtMs:null,...extra};value.stateDigest=runStateDigest(value);return value;}
function freshness(run,{readiness='ready',changed=false,attempt=0,assessedAtMs=1000}={}){const assessmentKind=run.state==='active'?'active_checkpoint':'suspension_recovery',originalDigest=D('original'),currentDigest=changed?D('changed'):originalDigest,recoveryEpisode=assessmentKind==='active_checkpoint'?{attemptOrdinal:0}:{startedAtMs:run.suspensionStartedAtMs,attemptOrdinal:attempt,dueAtMs:run.suspensionStartedAtMs+RECOVERY_OFFSETS[attempt-1]};const value={libraRunId:run.libraRunId,expectedState:{state:run.state,stateRevision:run.stateRevision,stateDigest:run.stateDigest},assessmentKind,recoveryPolicy:policy(),recoveryEpisode,assessedAtMs,currentDecisionHead:{snapshotDigest:D('head')},originalBasis:{comparableBasisDigest:originalDigest},readiness,unresolvedReasonCodes:readiness==='unresolved'?['required_query_unresolved']:[],dimensionResults:['acceptance_spec','product_scope','material_binding','material_control','output_requirement'].map((dimension)=>({dimension,result:readiness==='unresolved'?'unresolved':changed?'changed':'same',evidenceDigest:D(dimension)})),comparison:readiness==='unresolved'?'unresolved':changed?'changed':'same'};if(readiness==='ready')value.currentBasis={comparableBasisDigest:currentDigest};value.assessmentId=canonicalDigest({schema:'libra.run-freshness-assessment-id@1',libraRunId:value.libraRunId,expectedStateRevision:run.stateRevision,assessmentKind,attemptOrdinal:attempt,currentDecisionHeadDigest:value.currentDecisionHead.snapshotDigest});value.assessmentDigest=canonicalDigest(value);return value;}
function priorityIntent(run,requested='expedited'){const value={libraRunId:run.libraRunId,actorId:'actor-1',idempotencyKey:'key-1',expectedPriorityClass:run.priorityClass,requestedPriorityClass:requested,intentKind:requested==='expedited'?'accelerate':'cancel_acceleration',issuedAtMs:100};value.intentId=canonicalDigest({schema:'libra.run-priority-intent-id@1',libraRunId:value.libraRunId,actorId:value.actorId,idempotencyKey:value.idempotencyKey});value.intentDigest=canonicalDigest(value);return value;}
function terminal(run){const member={workId:'work-1',planId:'plan-1',workBasisDigest:D('work-basis'),terminalEventId:'event-1',capabilityRef:'helix://capabilities/libra/test/v1',failureClass:'permanent',failureCode:'exhausted',attemptCount:1,retryPolicyDigest:D('retry-policy'),terminalEvidenceDigest:D('terminal-attempt')};member.memberDigest=canonicalDigest({schema:'libra.run-terminal-blocker-member@1',...member});const value={libraRunId:run.libraRunId,executionBasisDigest:run.executionBasisDigest,blockerKind:'capability_exhausted',blockedWorks:[member],assessedAtMs:100};value.blockerSetDigest=canonicalDigest({schema:'libra.run-terminal-blocker-set@1',libraRunId:value.libraRunId,executionBasisDigest:value.executionBasisDigest,blockerKind:value.blockerKind,items:value.blockedWorks});value.evidenceId=canonicalDigest({schema:'libra.run-terminal-delivery-evidence-id@1',libraRunId:value.libraRunId,executionBasisDigest:value.executionBasisDigest,blockerKind:value.blockerKind,blockerSetDigest:value.blockerSetDigest,assessedAtMs:value.assessedAtMs});return withDigest(value,'evidenceDigest');}
function decision(run,transitionKind,evidence,newPriority){return buildRunLifecycleDecision({libraRunId:run.libraRunId,expectedStateRevision:run.stateRevision,expectedStateDigest:run.stateDigest,transitionKind,newPriority,transitionEvidence:evidence,expectedAdmissionHeadRevision:3,expectedActiveScopeSetDigest:D('active-set')});}

test('confirms same active basis and starts a bounded suspension episode for unresolved basis',()=>{const run=current(),confirmed=applyRunLifecycleDecision(run,decision(run,'freshness_confirmed',freshness(run)));assert.equal(confirmed.state,'active');assert.equal(confirmed.transitionKind,'freshness_confirmed');const suspended=applyRunLifecycleDecision(run,decision(run,'suspend',freshness(run,{readiness:'unresolved'})));assert.equal(suspended.state,'suspended');assert.equal(suspended.recoveryAttemptOrdinal,0);assert.equal(suspended.recoveryNextDueAtMs,1000+RECOVERY_OFFSETS[0]);assert.equal(suspended.recoveryPolicyRef,'libra.run-recovery.beta@1');});

test('persists recovery attempts, resumes on same basis, and freezes exactly at attempt five',()=>{let run=applyRunLifecycleDecision(current(),decision(current(),'suspend',freshness(current(),{readiness:'unresolved'})));for(let attempt=1;attempt<=4;attempt++){const evidence=freshness(run,{readiness:'unresolved',attempt,assessedAtMs:run.suspensionStartedAtMs+RECOVERY_OFFSETS[attempt-1]});run=applyRunLifecycleDecision(run,decision(run,'recovery_reassessed',evidence));assert.equal(run.state,'suspended');assert.equal(run.recoveryAttemptOrdinal,attempt);}const fifth=freshness(run,{readiness:'unresolved',attempt:5,assessedAtMs:run.suspensionStartedAtMs+RECOVERY_OFFSETS[4]}),frozen=applyRunLifecycleDecision(run,decision(run,'freeze',fifth));assert.equal(frozen.state,'frozen');assert.equal(frozen.recoveryAttemptOrdinal,5);assert.equal(frozen.recoveryNextDueAtMs,null);const forged={...fifth,expectedState:{state:frozen.state,stateRevision:frozen.stateRevision,stateDigest:frozen.stateDigest}};forged.assessmentId=canonicalDigest({schema:'libra.run-freshness-assessment-id@1',libraRunId:forged.libraRunId,expectedStateRevision:frozen.stateRevision,assessmentKind:forged.assessmentKind,attemptOrdinal:5,currentDecisionHeadDigest:forged.currentDecisionHead.snapshotDigest});forged.assessmentDigest=canonicalDigest(Object.fromEntries(Object.entries(forged).filter(([key])=>key!=='assessmentDigest')));assert.throws(()=>applyRunLifecycleDecision(frozen,decision(frozen,'resume',forged)),(error)=>error.code==='P9_RUN_LIFECYCLE_ILLEGAL_STATE');});

test('resumes a suspended Run only with the next ready/same recovery assessment',()=>{const active=current(),suspended=applyRunLifecycleDecision(active,decision(active,'suspend',freshness(active,{readiness:'unresolved'}))),evidence=freshness(suspended,{attempt:1,assessedAtMs:suspended.recoveryNextDueAtMs}),resumed=applyRunLifecycleDecision(suspended,decision(suspended,'resume',evidence));assert.equal(resumed.state,'active');assert.equal(resumed.recoveryNextDueAtMs,null);assert.equal(resumed.suspensionStartedAtMs,suspended.suspensionStartedAtMs);});

test('routes changed comparable basis to replacement admission instead of lifecycle',()=>{const run=current();assert.throws(()=>applyRunLifecycleDecision(run,decision(run,'freshness_confirmed',freshness(run,{changed:true}))),(error)=>error.code==='P9_RUN_REPLACEMENT_REQUIRED');});

test('reprioritizes active Run only with a matching typed intent',()=>{const run=current(),intent=priorityIntent(run),next=applyRunLifecycleDecision(run,decision(run,'set_priority',intent,{priorityClass:'expedited',priorityIntentDigest:intent.intentDigest}));assert.equal(next.priorityClass,'expedited');assert.equal(next.executionBasisDigest,run.executionBasisDigest);assert.equal(next.transitionKind,'reprioritized');const suspended=current('suspended');const rejected=priorityIntent(suspended);assert.throws(()=>applyRunLifecycleDecision(suspended,decision(suspended,'set_priority',rejected,{priorityClass:'expedited',priorityIntentDigest:rejected.intentDigest})),(error)=>error.code==='P9_RUN_PRIORITY_INTENT');});

test('allows direct active freeze only with terminal delivery evidence',()=>{const run=current(),frozen=applyRunLifecycleDecision(run,decision(run,'freeze',terminal(run)));assert.equal(frozen.state,'frozen');assert.throws(()=>applyRunLifecycleDecision(current('suspended'),decision(current('suspended'),'freeze',terminal(current('suspended')))),(error)=>error.code==='P9_RUN_LIFECYCLE_ILLEGAL_STATE');});

test('completes active or suspended Run with accepted message and forms durable Result digest',()=>{for(const run of [current(),current('suspended')]){const evidence={messageId:D(`accepted-${run.state}`),libraRunId:run.libraRunId,receiptId:'receipt-1'},completed=applyRunLifecycleDecision(run,decision(run,'complete',evidence)),result=buildRunLifecycleResult({decisionId:decision(run,'complete',evidence).decisionId,libraRunId:run.libraRunId,previousStateRevision:run.stateRevision,previousStateDigest:run.stateDigest,committedState:completed.state,committedStateRevision:completed.stateRevision,committedStateDigest:completed.stateDigest,committedAdmissionHeadRevision:4,activeScopeSetDigest:D('empty-set'),deliveryReceiptId:'receipt-1',terminalAtMs:100});assert.equal(completed.state,'completed');assert.equal(result.resultDigest,canonicalDigest(Object.fromEntries(Object.entries(result).filter(([key])=>key!=='resultDigest'))));}});

test('rejects stale fences, arbitrary evidence refs, early recovery, and digest tampering',()=>{const run=current();assert.throws(()=>decision(run,'suspend',{schemaRef:'legacy',evidenceId:'e',evidenceDigest:D('e')}),(error)=>error.code==='P9_RUN_LIFECYCLE_EVIDENCE');const stale=buildRunLifecycleDecision({libraRunId:run.libraRunId,expectedStateRevision:2,expectedStateDigest:run.stateDigest,transitionKind:'suspend',transitionEvidence:freshness(run,{readiness:'unresolved'}),expectedAdmissionHeadRevision:1,expectedActiveScopeSetDigest:D('set')});assert.throws(()=>applyRunLifecycleDecision(run,stale),(error)=>error.code==='P9_RUN_LIFECYCLE_STALE');const suspended=applyRunLifecycleDecision(run,decision(run,'suspend',freshness(run,{readiness:'unresolved'}))),early=freshness(suspended,{readiness:'unresolved',attempt:1,assessedAtMs:suspended.suspensionStartedAtMs});assert.throws(()=>decision(suspended,'recovery_reassessed',early),(error)=>error.code==='P9_RUN_FRESHNESS_EARLY');const broken=freshness(run);broken.assessmentDigest=D('broken');assert.throws(()=>decision(run,'freshness_confirmed',broken),(error)=>error.code==='P9_RUN_LIFECYCLE_EVIDENCE_DIGEST');});
