import { FormEvent, useCallback, useEffect, useState } from 'react';
import { AdminApiError, helixAdminApi, type FormationSubject, type FormationSummary, type Shelf } from './api';
import RatingControl from './RatingControl';

type SessionState = 'checking' | 'required' | 'ready';
type ProjectionState = { status:'ready'|'rebuilding'|'stale'; asOfMs:number };
const emptySummary:FormationSummary={totalCount:0,waitingCount:0,inProgressCount:0,completedCount:0};
function formatTime(value:number){return value>0?new Intl.DateTimeFormat('zh-CN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'—';}
function progress(item:FormationSubject){const value=item.nextAction.progress;if(!value||value.mode!=='determinate'||!value.totalValue)return null;return Math.min(100,Math.round(((value.currentValue||0)/value.totalValue)*100));}
function canChooseShelf(item:FormationSubject){return item.routingState==='unresolved'&&Number.isSafeInteger(item.routingDecisionHeadRevision)&&Boolean(item.routingDecisionHeadDigest);}

type TableProps={items:FormationSubject[];shelves:Shelf[];loading:boolean;onChoose:(item:FormationSubject,shelfId:string)=>void;onExpedite:(item:FormationSubject,value:boolean)=>void;onChooseIdentity:(item:FormationSubject,tmdbMovieId:string)=>void};
function MediaTable({items,shelves,loading,onChoose,onExpedite,onChooseIdentity}:TableProps){
  const [targets,setTargets]=useState<Record<string,string>>({}),[identityIds,setIdentityIds]=useState<Record<string,string>>({});
  return <div className="formation-table-wrap"><table className="formation-table"><thead><tr><th>媒体名称</th><th>我的评分</th><th>目标收藏夹</th><th>媒体数</th><th>整理要求</th><th>整理动作</th><th>添加时间</th><th>下一步动作</th></tr></thead><tbody>{items.map((item)=>{const percent=progress(item);return <tr key={item.subjectId}>
    <td><strong>{item.displayIdentity}</strong></td>
    <td><RatingControl targetType="subject" targetId={item.subjectId} label={item.displayIdentity} initialRating={item.myRating} initialSource={item.myRatingSource} initialRevision={item.myRatingRevision}/></td>
    <td>{item.targetShelfId?(item.targetShelfName||shelves.find((s)=>s.shelfId===item.targetShelfId)?.name||'已选收藏夹'):canChooseShelf(item)?<div className="manual-shelf"><select aria-label={`${item.displayIdentity}的目标收藏夹`} value={targets[item.subjectId]||shelves[0]?.shelfId||''} onChange={(event)=>setTargets((current)=>({...current,[item.subjectId]:event.target.value}))}>{shelves.map((shelf)=><option key={shelf.shelfId} value={shelf.shelfId}>{shelf.name}</option>)}</select><button type="button" disabled={loading||!shelves.length} onClick={()=>onChoose(item,targets[item.subjectId]||shelves[0]?.shelfId)}>选择</button></div>:<small>{item.routingState==='preparing'?'等待发布文件来源的收藏架分拣策略':'等待路由结果'}</small>}</td>
    <td>{item.primaryMaterialCount}</td><td>{item.organizingRequirement}</td><td>{item.organizingAction}</td><td>{formatTime(item.addedAtMs)}</td>
    <td><strong>{item.nextAction.label}</strong>{percent===null?<>{item.nextAction.progress?.mode==='indeterminate'&&<progress aria-label={`${item.displayIdentity}正在整理`}/>}<small>{item.nextAction.state}</small></>:<><progress max={100} value={percent} aria-label={`${item.displayIdentity}整理进度 ${percent}%`}/><small>{percent}%</small></>}{item.productIdentityIssue&&item.currentRun&&<div className="manual-shelf"><label><span className="sr-only">TMDB Movie ID</span><input aria-label={`${item.displayIdentity}的 TMDB Movie ID`} inputMode="numeric" placeholder="TMDB Movie ID" value={identityIds[item.subjectId]||''} onChange={(event)=>setIdentityIds((current)=>({...current,[item.subjectId]:event.target.value.replace(/\D/g,'')}))}/></label><button type="button" disabled={loading||!/^\d+$/.test(identityIds[item.subjectId]||'')} onClick={()=>onChooseIdentity(item,identityIds[item.subjectId])}>验证此身份</button>{item.productIdentityIssue.candidates.map((candidate)=><button type="button" key={candidate.providerKey} disabled={loading} onClick={()=>onChooseIdentity(item,candidate.providerKey)}>{candidate.displayTitle}{candidate.releaseYear?` (${candidate.releaseYear})`:''}</button>)}</div>}{item.currentRun?.state==='active'&&!item.handoffB&&<button className="surface-action" type="button" disabled={loading} onClick={()=>onExpedite(item,item.currentRun?.priorityClass!=='expedited')}>{item.currentRun.priorityClass==='expedited'?'取消加快':'加快整理'}</button>}</td>
  </tr>;})}</tbody></table></div>;
}

export default function FormationPage(){
  const [session,setSession]=useState<SessionState>('checking'),[apiKey,setApiKey]=useState(''),[items,setItems]=useState<FormationSubject[]>([]),[completed,setCompleted]=useState<FormationSubject[]>([]),[summary,setSummary]=useState<FormationSummary>(emptySummary),[shelves,setShelves]=useState<Shelf[]>([]),[expanded,setExpanded]=useState(()=>localStorage.getItem('formation-completed-expanded')==='true'),[activeCursor,setActiveCursor]=useState<string|null>(null),[completedCursor,setCompletedCursor]=useState<string|null>(null),[projection,setProjection]=useState<ProjectionState|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{const [active,shelfResult]=await Promise.all([helixAdminApi.listFormation('active'),helixAdminApi.listShelves()]);setItems(active.items);setActiveCursor(active.nextCursor);setSummary(active.summary);setProjection(active.projection);setShelves(shelfResult.items.filter((item)=>item.status==='active'));if(expanded){const done=await helixAdminApi.listFormation('completed');setCompleted(done.items);setCompletedCursor(done.nextCursor);}setSession('ready');}catch(cause){if(cause instanceof AdminApiError&&cause.status===401)setSession('required');else setError(cause instanceof Error?cause.message:'媒体整理工作区读取失败。');}finally{setLoading(false);}},[expanded]);
  useEffect(()=>{void load();},[load]);
  async function signIn(event:FormEvent){event.preventDefault();setLoading(true);setError('');try{await helixAdminApi.createSession(apiKey.trim());setApiKey('');await load();}catch(cause){setError(cause instanceof Error?cause.message:'管理凭据验证失败。');setLoading(false);}}
  async function choose(item:FormationSubject,shelfId:string){if(!shelfId)return;setLoading(true);try{await helixAdminApi.chooseShelf(item,shelfId);await load();}catch(cause){setError(cause instanceof Error?cause.message:'收藏夹选择失败。');setLoading(false);}}
  async function expedite(item:FormationSubject,value:boolean){setLoading(true);try{await helixAdminApi.setRunExpedited(item,value);await load();}catch(cause){setError(cause instanceof Error?cause.message:'整理优先级修改失败。');setLoading(false);}}
  async function chooseIdentity(item:FormationSubject,tmdbMovieId:string){setLoading(true);try{await helixAdminApi.chooseProductIdentity(item,tmdbMovieId);await load();}catch(cause){setError(cause instanceof Error?cause.message:'媒体身份确认失败。');setLoading(false);}}
  async function toggleCompleted(){const value=!expanded;setExpanded(value);localStorage.setItem('formation-completed-expanded',String(value));if(value){setLoading(true);try{const result=await helixAdminApi.listFormation('completed');setCompleted(result.items);setCompletedCursor(result.nextCursor);}finally{setLoading(false);}}}
  async function loadMoreCompleted(){if(!completedCursor)return;setLoading(true);try{const result=await helixAdminApi.listFormation('completed',completedCursor);setCompleted((current)=>[...current,...result.items]);setCompletedCursor(result.nextCursor);}finally{setLoading(false);}}
  async function loadMoreActive(){if(!activeCursor)return;setLoading(true);try{const result=await helixAdminApi.listFormation('active',activeCursor);setItems((current)=>[...current,...result.items]);setActiveCursor(result.nextCursor);setProjection(result.projection);}finally{setLoading(false);}}
  if(session==='checking')return <section className="source-page source-page-loading" aria-live="polite">正在读取媒体整理工作区…</section>;
  if(session==='required')return <section className="source-page auth-stage"><div className="auth-card"><p className="eyebrow">本机管理会话</p><h1>媒体整理工作区</h1><form onSubmit={signIn} className="auth-form"><label><span>管理凭据</span><input type="password" value={apiKey} onChange={(event)=>setApiKey(event.target.value)} required/></label><button type="submit" disabled={loading||!apiKey.trim()}>进入管理台</button></form>{error&&<p className="form-error" role="alert">{error}</p>}</div></section>;
  return <section className="source-page formation-page"><header className="source-hero"><div><p className="eyebrow">媒体整理</p><h1>媒体整理工作区</h1></div><button className="surface-action" type="button" onClick={()=>void load()} disabled={loading}>{loading?'正在刷新…':'刷新'}</button></header>
    {projection&&<p className="formation-projection-state" aria-live="polite">{projection.status==='ready'?'展示状态已更新':projection.status==='rebuilding'?'后台正在重建展示状态':'展示状态暂时滞后'} · {formatTime(projection.asOfMs)}</p>}
    <div className="source-facts" aria-label="整理状态摘要"><div><span>待整理</span><strong>{summary.waitingCount}</strong></div><div><span>整理中</span><strong>{summary.inProgressCount}</strong></div><div><span>已完成整理</span><strong>{summary.completedCount}</strong></div></div>{error&&<p className="form-error" role="alert">{error}</p>}
    <section className="formation-ledger"><div className="source-registry-heading"><div><p className="eyebrow">当前工作</p><h2>待整理媒体</h2></div><span>当前显示 {items.length} 条</span></div>{items.length?<><MediaTable items={items} shelves={shelves} loading={loading} onChoose={choose} onExpedite={expedite} onChooseIdentity={chooseIdentity}/>{activeCursor&&<button className="surface-action" type="button" onClick={()=>void loadMoreActive()} disabled={loading}>加载更多待整理媒体</button>}</>:<div className="source-empty"><strong>当前没有待整理媒体</strong></div>}</section>
    <section className="formation-ledger"><div className="source-registry-heading"><div><p className="eyebrow">历史结果</p><h2>已完成整理</h2></div><button className="surface-action" type="button" aria-expanded={expanded} onClick={()=>void toggleCompleted()}>{expanded?'收起':'展开'}（{summary.completedCount}）</button></div>{expanded&&<>{completed.length?<MediaTable items={completed} shelves={shelves} loading={loading} onChoose={choose} onExpedite={expedite} onChooseIdentity={chooseIdentity}/>:<div className="source-empty"><strong>尚无完成条目</strong></div>}{completedCursor&&<button className="surface-action" type="button" onClick={()=>void loadMoreCompleted()} disabled={loading}>加载更多</button>}</>}</section>
  </section>;
}
