import {FormEvent,useCallback,useEffect,useState} from 'react';
import {AdminApiError,helixAdminApi,type JsonValue,type OffdeckCase,type OffdeckCandidate,type OffdeckDuplicateGroup,type OffdeckPolicy,type OffdeckReview} from './api';

type RuleDraft={ruleId:string;shelfScope:'all'|'selected';shelfIds:string;conditionJson:string};
const ruleTemplate=(kind:'rating_and_collection_age'|'disliked_person'|'unresolved_care'|'retention_age'):RuleDraft=>({
  ruleId:`rule-${crypto.randomUUID()}`,shelfScope:'all',shelfIds:'',conditionJson:JSON.stringify({kind,parameters:kind==='rating_and_collection_age'?{maxRating:2,minimumAgeDays:365}:kind==='disliked_person'?{maximumPreferenceLevel:-1}:{minimumAgeDays:365}},null,2),
});

export default function OffdeckPage(){
  const [session,setSession]=useState<'checking'|'required'|'ready'>('checking');
  const [apiKey,setApiKey]=useState('');
  const [policy,setPolicy]=useState<OffdeckPolicy|null>(null);
  const [candidates,setCandidates]=useState<OffdeckCandidate[]>([]);
  const [groups,setGroups]=useState<OffdeckDuplicateGroup[]>([]);
  const [groupSelection,setGroupSelection]=useState<Record<string,string[]>>({});
  const [cases,setCases]=useState<OffdeckCase[]>([]);
  const [review,setReview]=useState<OffdeckReview|null>(null);
  const [ruleDrafts,setRuleDrafts]=useState<RuleDraft[]>([]);
  const [policyStatus,setPolicyStatus]=useState<'active'|'disabled'>('disabled');
  const [duplicateScheduleEnabled,setDuplicateScheduleEnabled]=useState(false);
  const [error,setError]=useState('');
  const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{
    setBusy(true);setError('');
    try{
      const [p,c,k]=await Promise.all([helixAdminApi.getOffdeckPolicy(),helixAdminApi.listOffdeckCandidates(),helixAdminApi.listOffdeckCases()]);
      setPolicy(p);setPolicyStatus(p.status);setDuplicateScheduleEnabled(p.duplicateScheduleEnabled);setRuleDrafts(p.entryRules.map(rule=>({ruleId:rule.ruleId,shelfScope:rule.shelfScope,shelfIds:rule.shelfIds.join(', '),conditionJson:JSON.stringify(rule.condition,null,2)})));setCandidates(c.candidates);setGroups(c.duplicateGroups);setCases(k.items);setSession('ready');
      const id=new URLSearchParams(location.search).get('review');if(id)setReview(await helixAdminApi.getOffdeckReview(id));
    }catch(cause){if(cause instanceof AdminApiError&&cause.status===401)setSession('required');else setError(cause instanceof Error?cause.message:'退出收藏读取失败。');}
    finally{setBusy(false);}
  },[]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{if(!review||review.state!=='preparing')return;const timer=window.setInterval(()=>{void helixAdminApi.getOffdeckReview(review.reviewId).then(setReview).catch(cause=>setError(cause instanceof Error?cause.message:'退出范围准备失败。'));},500);return()=>window.clearInterval(timer);},[review]);
  async function signIn(event:FormEvent){event.preventDefault();await helixAdminApi.createSession(apiKey);setApiKey('');await load();}
  async function action(run:()=>Promise<unknown>){setBusy(true);setError('');try{await run();await load();}catch(cause){setError(cause instanceof Error?cause.message:'操作未完成。');}finally{setBusy(false);}}
  function toggleMember(groupId:string,shelfEntryId:string){setGroupSelection(current=>{const selected=new Set(current[groupId]||[]);selected.has(shelfEntryId)?selected.delete(shelfEntryId):selected.add(shelfEntryId);return {...current,[groupId]:[...selected].sort()};});}
  async function openCandidate(item:OffdeckCandidate){
    let body:Record<string,unknown>;
    if(item.candidate_kind==='entry')body={originKind:'candidate',originRef:item.candidate_id,idempotencyKey:`offdeck-candidate:${item.candidate_id}`};
    else {const selected=groupSelection[item.duplicate_group_id||'']||[];if(selected.length===0)throw new Error('请先选择重复组中需要退出的收藏。');body={shelfEntryIds:selected,originKind:'duplicate_group',originRef:item.duplicate_group_id,idempotencyKey:`offdeck-duplicate:${item.duplicate_group_id}:${selected.join(',')}`};}
    const value=await helixAdminApi.createOffdeckReview({...body,actorId:'admin'});setReview(value);history.replaceState(null,'',`/offdeck?review=${encodeURIComponent(value.reviewId)}`);
  }
  async function savePolicy(){
    if(!policy)throw new Error('退出规则尚未加载。');
    const entryRules=ruleDrafts.map((draft,index)=>{let condition:JsonValue;try{condition=JSON.parse(draft.conditionJson) as JsonValue;}catch{throw new Error(`第 ${index+1} 条规则不是有效JSON。`);}return {ruleId:draft.ruleId,shelfScope:draft.shelfScope,shelfIds:draft.shelfScope==='selected'?draft.shelfIds.split(',').map(value=>value.trim()).filter(Boolean):[],condition};});
    await helixAdminApi.publishOffdeckPolicy({expectedRevision:policy.revision,status:policyStatus,duplicateScheduleEnabled,entryRules,idempotencyKey:`offdeck-policy:${crypto.randomUUID()}`});
  }
  if(session==='checking')return <section className="source-page source-page-loading">正在读取退出收藏事实…</section>;
  if(session==='required')return <section className="source-page auth-stage"><div className="auth-card"><p className="eyebrow">本机管理会话</p><h1>退出收藏</h1><form onSubmit={signIn} className="auth-form"><label><span>管理凭据</span><input type="password" value={apiKey} onChange={e=>setApiKey(e.target.value)} required/></label><button>进入管理台</button></form></div></section>;
  const openCandidates=candidates.filter(item=>item.state==='open');
  return <section className="source-page">
    <header className="source-hero"><div><p className="eyebrow">Collection Exit · Arca</p><h1>审阅清楚，再执行不可逆退出</h1><p>推荐和直接退出共用同一条 Reservation、Scope 与 Authorization 安全链。</p></div><button className="surface-action" onClick={()=>void load()} disabled={busy}>刷新</button></header>
    {error&&<p className="form-error" role="alert">{error}</p>}
    <section className="source-card"><div className="source-card-heading"><div><p className="eyebrow">退出规则</p><h2>{policy?.status==='active'?'自动建议已启用':'默认关闭'}</h2></div><button onClick={()=>void action(savePolicy)} disabled={busy}>保存并发布revision</button></div><p>规则按顺序评估；任一必要Fact未知时不会产生建议。手动重复检测始终可用。</p><div className="form-grid"><label><span>Entry Policy</span><select value={policyStatus} onChange={event=>setPolicyStatus(event.target.value as 'active'|'disabled')}><option value="disabled">关闭</option><option value="active">启用</option></select></label><label><span>周期重复检测</span><input type="checkbox" checked={duplicateScheduleEnabled} onChange={event=>setDuplicateScheduleEnabled(event.target.checked)}/></label></div>{ruleDrafts.map((draft,index)=><article className="source-row" key={draft.ruleId}><div className="form-grid"><label><span>Rule ID</span><input value={draft.ruleId} onChange={event=>setRuleDrafts(items=>items.map((item,i)=>i===index?{...item,ruleId:event.target.value}:item))}/></label><label><span>Shelf范围</span><select value={draft.shelfScope} onChange={event=>setRuleDrafts(items=>items.map((item,i)=>i===index?{...item,shelfScope:event.target.value as 'all'|'selected'}:item))}><option value="all">全部Shelf</option><option value="selected">指定Shelf</option></select></label>{draft.shelfScope==='selected'&&<label><span>Shelf IDs（逗号分隔）</span><input value={draft.shelfIds} onChange={event=>setRuleDrafts(items=>items.map((item,i)=>i===index?{...item,shelfIds:event.target.value}:item))}/></label>}<label><span>Closed Condition AST（支持all / any）</span><textarea rows={7} value={draft.conditionJson} onChange={event=>setRuleDrafts(items=>items.map((item,i)=>i===index?{...item,conditionJson:event.target.value}:item))}/></label></div><button onClick={()=>setRuleDrafts(items=>items.filter((_,i)=>i!==index))}>移除规则</button></article>)}<div className="button-row"><button onClick={()=>setRuleDrafts(items=>[...items,ruleTemplate('rating_and_collection_age')])}>低评分+收藏时间</button><button onClick={()=>setRuleDrafts(items=>[...items,ruleTemplate('disliked_person')])}>不喜欢的人物</button><button onClick={()=>setRuleDrafts(items=>[...items,ruleTemplate('unresolved_care')])}>长期健康问题</button><button onClick={()=>setRuleDrafts(items=>[...items,ruleTemplate('retention_age')])}>收藏保留时间</button><button onClick={()=>void action(()=>helixAdminApi.evaluateOffdeck())}>立即评估</button><button onClick={()=>void action(()=>helixAdminApi.detectOffdeckDuplicates())}>检测重复收藏</button></div></section>
    <section className="source-card"><div className="source-card-heading"><div><p className="eyebrow">退出建议</p><h2>{openCandidates.length} 条待审阅</h2></div></div>{openCandidates.length===0?<p>当前没有开放建议。</p>:openCandidates.map(item=>{const group=item.candidate_kind==='duplicate_group'?groups.find(value=>value.duplicate_group_id===item.duplicate_group_id):null;return <article className="source-row" key={item.candidate_id}><div><strong>{item.candidate_kind==='entry'?'收藏条目':'重复收藏组'}</strong><small>{item.shelf_entry_id||item.duplicate_group_id}</small>{group&&<fieldset><legend>选择需要退出的成员（系统不替你决定保留项）</legend>{group.members.map(member=><label key={member.shelf_entry_id}><input type="checkbox" checked={(groupSelection[group.duplicate_group_id]||[]).includes(member.shelf_entry_id)} onChange={()=>toggleMember(group.duplicate_group_id,member.shelf_entry_id)}/>{member.shelf_entry_id}</label>)}</fieldset>}</div><div className="button-row"><button onClick={()=>void action(()=>openCandidate(item))}>进入审阅</button><button onClick={()=>void action(()=>item.candidate_kind==='entry'?helixAdminApi.suppressOffdeckCandidate(item.candidate_id):helixAdminApi.whitelistOffdeckDuplicate(item.duplicate_group_id!))}>继续保留</button></div></article>;})}</section>
    {review&&<section className={`source-card ${review.state==='awaiting_escalation'?'danger-stage':''}`}><div className="source-card-heading"><div><p className="eyebrow">{review.state==='awaiting_escalation'?'高量退出 · 独立二次确认':'审阅与授权'}</p><h2>{review.state}</h2></div></div>{review.state==='awaiting_escalation'&&<p role="alert">本次范围命中高量阈值。请再次核对数量和空间；这一步不能由普通授权动作绕过。</p>}{review.scopes.map(scope=><article key={scope.destructionScopeId}><strong>{scope.memberCount} 个Physical Material · {(scope.totalBytes/1024/1024/1024).toFixed(2)} GiB</strong>{scope.materials.map(material=><p key={material.materialKey}>{material.role} · {material.location} · {material.deleteCondition}</p>)}</article>)}<div className="button-row">{review.state==='open'&&<button onClick={()=>void action(async()=>setReview(await helixAdminApi.confirmOffdeckSelection(review.reviewId,{actorId:'admin'})))}>确认范围</button>}{review.state==='awaiting_escalation'&&<button className="danger" onClick={()=>void action(async()=>setReview(await helixAdminApi.confirmOffdeckHighVolume(review.reviewId,{actorId:'admin'})))}>我已再次核对，确认高量退出</button>}{review.state==='selection_confirmed'&&<button className="danger" onClick={()=>void action(()=>helixAdminApi.authorizeOffdeck(review.reviewId))}>授权并开始退出</button>}{['preparing','open','selection_confirmed','awaiting_escalation'].includes(review.state)&&<button onClick={()=>void action(()=>helixAdminApi.cancelOffdeckReview(review.reviewId))}>取消审阅</button>}</div></section>}
    <section className="source-card"><div className="source-card-heading"><div><p className="eyebrow">退出进度</p><h2>{cases.length} 个Case</h2></div></div>{cases.length===0?<p>尚无退出执行。</p>:cases.map(item=><article className="source-row" key={item.offdeckCaseId}><div><strong>{item.shelfEntryId}</strong><small>{item.state} · recovery revision {item.recoveryRevision}</small>{item.blockedReason&&<p>阻塞原因：{item.blockedReason}{item.retryAtMs?` · ${new Date(item.retryAtMs).toLocaleString()} 后自动恢复`:''}</p>}</div>{item.state==='awaiting_reauthorization'&&<button onClick={()=>void action(async()=>{const value=await helixAdminApi.createOffdeckReview({caseId:item.offdeckCaseId,originKind:'reauthorization',originRef:item.offdeckCaseId,actorId:'admin',idempotencyKey:`offdeck-reauthorize:${item.offdeckCaseId}:${item.recoveryRevision}`});setReview(value);history.replaceState(null,'',`/offdeck?review=${encodeURIComponent(value.reviewId)}`);})}>重新授权同一Case</button>}</article>)}</section>
  </section>;
}
