import { FormEvent, useCallback, useEffect, useState } from 'react';
import { AdminApiError, helixAdminApi, type IntegrationState, type PerceptionRecord } from './api';

function time(value:number){return new Intl.DateTimeFormat('zh-CN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));}
function stars(value:number|null){return value===null?'—':'★'.repeat(value)+'☆'.repeat(5-value);}

export default function SettingsPage(){
  const [session,setSession]=useState<'checking'|'required'|'ready'>('checking'),[apiKey,setApiKey]=useState(''),[tab,setTab]=useState<'integrations'|'ratings'>('integrations');
  const [integration,setIntegration]=useState<IntegrationState|null>(null),[tmdb,setTmdb]=useState<IntegrationState|null>(null),[moviePilot,setMoviePilot]=useState<IntegrationState|null>(null),[records,setRecords]=useState<PerceptionRecord[]>([]),[nextCursor,setNextCursor]=useState<string|null>(null);
  const [userId,setUserId]=useState(''),[cookie,setCookie]=useState(''),[sourceFilter,setSourceFilter]=useState(''),[statusFilter,setStatusFilter]=useState('');
  const [tmdbCredentialKind,setTmdbCredentialKind]=useState<'api_key'|'access_token'>('access_token'),[tmdbCredential,setTmdbCredential]=useState('');
  const [tmdbLanguage,setTmdbLanguage]=useState('zh-CN');
  const [moviePilotEndpoint,setMoviePilotEndpoint]=useState(''),[moviePilotKey,setMoviePilotKey]=useState(''),[providerRequestRoot,setProviderRequestRoot]=useState(''),[providerOrganizedRoot,setProviderOrganizedRoot]=useState(''),[visibleLandingRoot,setVisibleLandingRoot]=useState('');
  const [ratingFilter,setRatingFilter]=useState(''),[targetFilter,setTargetFilter]=useState('');
  const [loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{const [configured,configuredTmdb,configuredMoviePilot,log]=await Promise.all([helixAdminApi.getIntegration('douban'),helixAdminApi.getIntegration('tmdb'),helixAdminApi.getIntegration('moviepilot'),helixAdminApi.listPerceptionRecords({limit:100,sourceKind:sourceFilter,resolutionStatus:statusFilter,rating:ratingFilter?Number(ratingFilter):undefined,targetType:targetFilter})]);
    setIntegration(configured);setTmdb(configuredTmdb);setTmdbLanguage(configuredTmdb.settings?.language||'zh-CN');setMoviePilot(configuredMoviePilot);setRecords(log.items);setNextCursor(log.nextCursor);setSession('ready');}catch(cause){if(cause instanceof AdminApiError&&cause.status===401)setSession('required');else setError(cause instanceof Error?cause.message:'设置读取失败。');}finally{setLoading(false);}},[sourceFilter,statusFilter,ratingFilter,targetFilter]);
  useEffect(()=>{void load();},[load]);
  async function signIn(event:FormEvent){event.preventDefault();try{await helixAdminApi.createSession(apiKey.trim());setApiKey('');await load();}catch(cause){setError(cause instanceof Error?cause.message:'管理凭据验证失败。');}}
  async function connect(event:FormEvent){event.preventDefault();setLoading(true);setError('');setNotice('');try{const proof=await helixAdminApi.testIntegration('douban',{kind:'douban',idempotencyKey:`douban-test:${crypto.randomUUID()}`,
      endpoint:'https://movie.douban.com',credential:{kind:'cookie',value:cookie},settings:{userId},timeoutMs:20_000});
    await helixAdminApi.configureIntegration('douban',{kind:'douban',idempotencyKey:`douban-configure:${proof.connectionProofId}`,expectedConfigRevision:integration?.configRevision||0,connectionProofId:proof.connectionProofId});
    setCookie('');setNotice('豆瓣连接已通过真实页面验证并保存。');await load();}catch(cause){setError(cause instanceof Error?cause.message:'豆瓣连接失败。');}finally{setLoading(false);}}
  async function sync(){setLoading(true);setError('');try{await helixAdminApi.syncDouban();setNotice('同步已进入后台队列；评分日志会随分页结果逐步增加。');window.setTimeout(()=>void load(),1200);}catch(cause){setError(cause instanceof Error?cause.message:'豆瓣同步未启动。');}finally{setLoading(false);}}
  async function disconnect(){if(!integration)return;setLoading(true);try{await helixAdminApi.disconnectIntegration('douban',{kind:'douban',idempotencyKey:`douban-disconnect:${integration.configRevision}`,expectedConfigRevision:integration.configRevision});setNotice('豆瓣连接已断开，历史评分事实仍保留。');await load();}catch(cause){setError(cause instanceof Error?cause.message:'断开失败。');}finally{setLoading(false);}}
  async function connectTmdb(event:FormEvent){event.preventDefault();setLoading(true);setError('');setNotice('');try{const proof=await helixAdminApi.testIntegration('tmdb',{kind:'tmdb',idempotencyKey:`tmdb-test:${crypto.randomUUID()}`,
      endpoint:'https://api.themoviedb.org/3',credential:{kind:tmdbCredentialKind,value:tmdbCredential},settings:{language:tmdbLanguage},timeoutMs:20_000});
    await helixAdminApi.configureIntegration('tmdb',{kind:'tmdb',idempotencyKey:`tmdb-configure:${proof.connectionProofId}`,expectedConfigRevision:tmdb?.configRevision||0,connectionProofId:proof.connectionProofId});
    setTmdbCredential('');setNotice('TMDB 已通过真实 Configuration API 验证并保存。');await load();}catch(cause){setError(cause instanceof Error?cause.message:'TMDB 连接失败。');}finally{setLoading(false);}}
  async function disconnectTmdb(){if(!tmdb)return;setLoading(true);try{await helixAdminApi.disconnectIntegration('tmdb',{kind:'tmdb',idempotencyKey:`tmdb-disconnect:${tmdb.configRevision}`,expectedConfigRevision:tmdb.configRevision});setNotice('TMDB 已断开；等待身份输入的Event会继续保持外部等待。');await load();}catch(cause){setError(cause instanceof Error?cause.message:'断开失败。');}finally{setLoading(false);}}
  async function connectMoviePilot(event:FormEvent){event.preventDefault();setLoading(true);setError('');setNotice('');try{const proof=await helixAdminApi.testIntegration('moviepilot',{kind:'moviepilot',idempotencyKey:`moviepilot-test:${crypto.randomUUID()}`,
      endpoint:moviePilotEndpoint,credential:{kind:'api_key',value:moviePilotKey},settings:{providerRequestSaveRoot:providerRequestRoot,providerOrganizedRoot,shelfDeckVisibleRoot:visibleLandingRoot},timeoutMs:20_000});
    await helixAdminApi.configureIntegration('moviepilot',{kind:'moviepilot',idempotencyKey:`moviepilot-configure:${proof.connectionProofId}`,expectedConfigRevision:moviePilot?.configRevision||0,connectionProofId:proof.connectionProofId});
    setMoviePilotKey('');setNotice('MoviePilot 与 External Landing 已完成真实能力及路径验证。');await load();}catch(cause){setError(cause instanceof Error?cause.message:'MoviePilot 连接失败。');}finally{setLoading(false);}}
  async function disconnectMoviePilot(){if(!moviePilot)return;setLoading(true);try{await helixAdminApi.disconnectIntegration('moviepilot',{kind:'moviepilot',idempotencyKey:`moviepilot-disconnect:${moviePilot.configRevision}`,expectedConfigRevision:moviePilot.configRevision});setNotice('MoviePilot 已断开；既有 Landing 文件未被删除。');await load();}catch(cause){setError(cause instanceof Error?cause.message:'断开失败。');}finally{setLoading(false);}}
  async function loadMore(){if(!nextCursor)return;const result=await helixAdminApi.listPerceptionRecords({cursor:nextCursor,limit:100,sourceKind:sourceFilter,resolutionStatus:statusFilter,rating:ratingFilter?Number(ratingFilter):undefined,targetType:targetFilter});setRecords((current)=>[...current,...result.items]);setNextCursor(result.nextCursor);}
  if(session==='checking')return <section className="source-page source-page-loading">正在读取系统设置…</section>;
  if(session==='required')return <section className="source-page auth-stage"><div className="auth-card"><p className="eyebrow">本机管理会话</p><h1>系统设置</h1><form className="auth-form" onSubmit={signIn}><label><span>管理凭据</span><input type="password" value={apiKey} onChange={(event)=>setApiKey(event.target.value)} required/></label><button>进入管理台</button></form>{error&&<p className="form-error" role="alert">{error}</p>}</div></section>;
  return <section className="source-page settings-page"><header className="source-hero"><div><p className="eyebrow">系统设置</p><h1>连接与可追溯记录</h1><p>连接动作与评分历史分开；评分日志始终只读。</p></div></header>
    <div className="settings-tabs" role="tablist"><button role="tab" aria-selected={tab==='integrations'} onClick={()=>setTab('integrations')}>连接与集成</button><button role="tab" aria-selected={tab==='ratings'} onClick={()=>setTab('ratings')}>评分日志</button></div>
    {error&&<p className="form-error" role="alert">{error}</p>}{notice&&<p className="form-notice" role="status">{notice}</p>}
    {tab==='integrations'?<div className="settings-panel-stack"><section className="settings-panel" aria-labelledby="douban-title"><div className="source-registry-heading"><div><p className="eyebrow">User Perception Provider</p><h2 id="douban-title">豆瓣</h2></div><span className={`integration-state ${integration?.configured?'active':'inactive'}`}>{integration?.configured?'已连接':'未连接'}</span></div>
      {integration?.configured?<div className="integration-summary"><p>账号：<strong>{integration.lastTestSummary?.identityProviderKey||'已验证'}</strong></p><p>配置 revision：{integration.configRevision}</p><div className="button-row"><button type="button" onClick={()=>void sync()} disabled={loading}>同步全部收藏评分</button><button type="button" className="danger-quiet" onClick={()=>void disconnect()} disabled={loading}>断开</button></div></div>:
      <form className="source-form" onSubmit={connect}><label><span>豆瓣用户 ID</span><input value={userId} onChange={(event)=>setUserId(event.target.value)} required/></label><label><span>Cookie</span><textarea value={cookie} onChange={(event)=>setCookie(event.target.value)} rows={4} required/><small>仅写入本机 Secret Store，不进入日志或评分事实。</small></label><button disabled={loading||!userId||cookie.length<8}>{loading?'正在真实验证…':'测试并连接'}</button></form>}
    </section><section className="settings-panel" aria-labelledby="tmdb-title"><div className="source-registry-heading"><div><p className="eyebrow">Identity, Metadata &amp; Artwork Provider</p><h2 id="tmdb-title">TMDB</h2></div><span className={`integration-state ${tmdb?.configured?'active':'inactive'}`}>{tmdb?.configured?'已连接':'未连接'}</span></div>
      {tmdb?.configured?<div className="integration-summary"><p>Endpoint：<strong>{tmdb.endpoint}</strong></p><p>语言：<strong>{tmdb.settings?.language||'zh-CN'}</strong></p><p>配置 revision：{tmdb.configRevision}</p><p>用于Movie身份、Metadata与海报补齐；凭据只保存在本机Secret Store。</p><div className="button-row"><button type="button" className="danger-quiet" onClick={()=>void disconnectTmdb()} disabled={loading}>断开</button></div></div>:
      <form className="source-form" onSubmit={connectTmdb}><label><span>首选语言</span><select value={tmdbLanguage} onChange={(event)=>setTmdbLanguage(event.target.value)}><option value="zh-CN">简体中文（zh-CN）</option><option value="zh-TW">繁体中文（zh-TW）</option><option value="en-US">English（en-US）</option></select><small>原始标题及有界替代标题仍会作为身份匹配证据。</small></label><label><span>凭据类型</span><select value={tmdbCredentialKind} onChange={(event)=>setTmdbCredentialKind(event.target.value as 'api_key'|'access_token')}><option value="access_token">Read Access Token</option><option value="api_key">API Key</option></select></label><label><span>{tmdbCredentialKind==='access_token'?'Read Access Token':'API Key'}</span><input type="password" value={tmdbCredential} onChange={(event)=>setTmdbCredential(event.target.value)} required/><small>通过TMDB官方Configuration API测试后才会保存。</small></label><button disabled={loading||tmdbCredential.length<8}>{loading?'正在真实验证…':'测试并连接'}</button></form>}
    </section><section className="settings-panel" aria-labelledby="moviepilot-title"><div className="source-registry-heading"><div><p className="eyebrow">External Acquisition Provider</p><h2 id="moviepilot-title">MoviePilot</h2></div><span className={`integration-state ${moviePilot?.configured?'active':'inactive'}`}>{moviePilot?.configured?'已连接':'未连接'}</span></div>
      {moviePilot?.configured&&moviePilot.landingBinding?<div className="integration-summary"><p>Endpoint：<strong>{moviePilot.endpoint}</strong></p><p>请求下载根：{moviePilot.landingBinding.providerRequestSaveRoot}</p><p>整理根：{moviePilot.landingBinding.providerOrganizedRoot}</p><p>ShelfDeck只读Landing：{moviePilot.landingBinding.shelfDeckVisibleRoot}</p><p>Binding revision：{moviePilot.landingBinding.bindingRevision}</p><p>Landing 与 Libra Workspace 始终独立；导入完成不会删除 Landing 原件。</p><div className="button-row"><button type="button" className="danger-quiet" onClick={()=>void disconnectMoviePilot()} disabled={loading}>断开</button></div></div>:
      <form className="source-form" onSubmit={connectMoviePilot}><label><span>Endpoint</span><input value={moviePilotEndpoint} onChange={(event)=>setMoviePilotEndpoint(event.target.value)} placeholder="http://nas:3000" required/></label><label><span>API Key</span><input type="password" value={moviePilotKey} onChange={(event)=>setMoviePilotKey(event.target.value)} required/></label><label><span>MoviePilot请求下载根</span><input value={providerRequestRoot} onChange={(event)=>setProviderRequestRoot(event.target.value)} placeholder="/downloads/shelfdeck" required/></label><label><span>MoviePilot整理根</span><input value={providerOrganizedRoot} onChange={(event)=>setProviderOrganizedRoot(event.target.value)} placeholder="/media/shelfdeck-landing" required/></label><label><span>ShelfDeck可见Landing根</span><input value={visibleLandingRoot} onChange={(event)=>setVisibleLandingRoot(event.target.value)} placeholder="/landing/moviepilot" required/><small>必须是同一整理目录的只读视图，且不得与Workspace、Material Field或Shelf Target重叠。</small></label><button disabled={loading||moviePilotKey.length<8||!moviePilotEndpoint||!providerRequestRoot||!providerOrganizedRoot||!visibleLandingRoot}>{loading?'正在验证…':'测试并连接'}</button></form>}
    </section></div>:<section className="settings-panel rating-log" aria-labelledby="rating-log-title"><div className="source-registry-heading"><div><p className="eyebrow">Immutable Ledger</p><h2 id="rating-log-title">评分日志</h2></div><span>{records.length} 条</span></div>
      <div className="log-filters"><label>来源<select value={sourceFilter} onChange={(event)=>setSourceFilter(event.target.value)}><option value="">全部</option><option value="douban">豆瓣</option><option value="shelfdeck_direct">ShelfDeck</option></select></label><label>星级<select value={ratingFilter} onChange={(event)=>setRatingFilter(event.target.value)}><option value="">全部</option>{[1,2,3,4,5].map((value)=><option key={value} value={value}>{value}星</option>)}</select></label><label>状态<select value={statusFilter} onChange={(event)=>setStatusFilter(event.target.value)}><option value="">全部</option><option value="matched">已匹配</option><option value="unmatched">未匹配</option><option value="ambiguous">有歧义</option><option value="superseded">已更正</option></select></label><label>目标<select value={targetFilter} onChange={(event)=>setTargetFilter(event.target.value)}><option value="">全部</option><option value="subject">上架Subject</option><option value="shelf_entry">收藏条目</option></select></label></div>
      {records.length===0?<div className="source-empty"><strong>还没有评分记录</strong><p>这里不会提供评分或同步按钮；请在上架进度或我的收藏中评分。</p></div>:<div className="formation-table-wrap"><table className="formation-table"><thead><tr><th>标题</th><th>评分</th><th>来源</th><th>状态</th><th>目标</th><th>记录时间</th></tr></thead><tbody>{records.map((record)=><tr key={record.perceptionId}><td><strong>{record.observedTitle}</strong><small>{record.recordKind}</small></td><td className="rating-text">{stars(record.rating)}</td><td>{record.sourceKind==='douban'?'豆瓣':'ShelfDeck'}</td><td>{record.resolutionStatus}</td><td>{record.targetType?`${record.targetType} · ${record.targetId}`:'未匹配'}</td><td>{time(record.committedAtMs)}</td></tr>)}</tbody></table></div>}
      {nextCursor&&<button className="surface-action" onClick={()=>void loadMore()}>加载更多</button>}
    </section>}
  </section>;
}
